---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: signoz-secrets
  namespace: infra
spec:
  encryptedData:
    SIGNOZ_TOKENIZER_JWT_SECRET: AgCEo/sYTU2DoIWhdG9rR1eBgzmPrdZ+49Gan/YZ4Pn6bs25nPq+boby/tYn8HQuwsfqcAUVRYdkKI29Q84pnzWLRNcpeK+nGWZr5SBNosTONWMcWWZYcLsfJfjtYPbDAN5ufowC3GwaaAcKR8I0pj6NWHQYI2v6eCPy6wH2XkdFOQ2YyGlQOnLS82gRK88YpxBwlXLviz1WTM+KDDSSeUQewn6e47nIkmYok/VNxjJzzP0jGyX38sHfxK0ZKbYpc5HH3cDEzDXDMVKVxDZWTDeWvr9X5XX8P5LzbCB//ExFAnvnUbOuE4c/xSCM9kHb+P3hUaMPm4Vc9sK3bp7lLN8mA8aPC4zajxXgxAoeePFJxIN4J0/XK10zxavw8SIP/vFejNNNAphK7sT6g0JXKn5PUMjanTF17EJp/Z6aZ6G+9jpNhbgkLyzhkCPFs0uOMtu818zp0eWRyIl65lsiZUH958r7IDxWNOfFCZv09A/JQnhFeNdL+wUGZ7dH6OJMDlkysVOFzPtHzU73IqWdzzl7LQm8OPzweEmTvQ8tRPqfKgS+n/yXtZpbasy6aO6u6Sw/yArnBQ59KhJBW6XfPIXHgnHKHaRaTAYith8c/Hzei3ugrXOvzpGqCugt/YXyE556JRtA5S9WCnGZhOuC7iHYHrBU7pqpmhTxyfChqSBUKIdDa2WJRLA+3ZobTfR3bcpFqxJDhl4qACLxriekq451O4pgbJX8R9tR63uhCssewu5t2eEXIESU2GFwPoQ+XvPiptkZ4BLMw78s3EEIj7fK
  template:
    metadata:
      name: signoz-secrets
      namespace: infra
