---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: verdaccio-htpasswd
  namespace: infra
spec:
  encryptedData:
    htpasswd: AgCRFl7sNrmq/y/E9R7958RmOShcOfKcFZzn33qQGb/JDJFY08L6Wmb+EucBzvb2Fh/ItPUmBlZVs2ws5Rokplh3WshT1CEph+nw9Ourgy8EHi8tZUsaWbqX4xcNrbaf6X9qmkMAIRxg2/pQ8oaPb3sj7KDN6ds4JN27+roPMbd3MLdeb0MhZ3rkKWwFOw8D7HReHCIdx2rEW7T9EUr/Q1VCatEOVRw28mdt6w7/nGHEJkVsbJJopwwicHD+bw2sUd2t31rbglt/0kH0XFOcEBut3hcVjvE1tASN+TVUM3n/HWsFwq9NISpnpDjnqXvMRSWZpV8WZqAat3/ZFGi3dZm/5dbV2pHeCZha+TuJrAsEOoZXqBabXpmoNLi+nsX+4U7zoSbNQi4lI28zMmQktcfFaby7Tw2aEu/LFqwAgv4qniaItmgyJy07GggpY3Wh/Gj6FZKctQQNOk5V7fdIC6uqsE8polcfgMsku4awEkbratqBc9IdWlJhsCbV6zuISQI2NEzmUtrpabxez1EbvAEpMBVfrk+OUIs1mOp2Z6hPRcx1dPTTdTbhOtRE1jTztIJLyiWn1Awe85SPBvqyhk0Fw+tatr5akMrUGALTMXlYirz4pR3Lbf5rJFLjY4LE93X2SXVnPtmXgTUrGlcyo/rGVt4TTA5NxiSc6RU8Iz04xRRsLynvYC66eYBFdkGazmCRwqFEJHDrd6ruxxr46pnujbgwWMj8a3HJPtffcEctxAO4SObluUIF5IWSixYSROOIaGmaV53kPQrbYjOxulI9nqg=
  template:
    metadata:
      name: verdaccio-htpasswd
      namespace: infra
