{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "codefresh.fullname" . }}-migrate
  labels:
    {{- include "codefresh.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "codefresh.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: migrate
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        command: ["bin/codefresh", "eval", "Codefresh.Release.migrate()"]
        env:
        - name: DB_HOST
          value: {{ .Values.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.keys.dbUser }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.keys.dbPassword }}
        - name: DB_NAME
          value: {{ .Values.database.name | quote }}
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.keys.secretKeyBase }}
        - name: GUARDIAN_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.keys.guardianSecretKey }}
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.keys.redisUrl }}
        - name: PHX_HOST
          value: {{ .Values.domain | quote }}
        - name: PORT
          value: {{ .Values.backend.port | quote }}
        resources:
          {{- toYaml .Values.migrate.resources | nindent 10 }}
{{- end }}
