defmodule Codefresh.Review.ReviewItem do
  @moduledoc """
  One row in the freeball review queue — a pending verdict on a freeball node
  generated by the Stage-5 runner. Backs US-088 (queue listing) and US-089
  (claim / approve / reject). SLA fields (assigned_at, sla_warning_sent_at)
  back US-140 / US-141.

  Mirrors:
    * `priv/repo/migrations/20260421000016_create_review_queue.exs`
    * `priv/repo/migrations/20260421000045_add_review_queue_sla_fields.exs`
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @statuses ~w(pending claimed approved rejected promoted)

  schema "review_queue" do
    field :status, :string, default: "pending"
    field :priority, :integer, default: 0
    field :claimed_at, :utc_datetime
    field :resolved_at, :utc_datetime
    field :resolution_notes, :string
    field :assigned_at, :utc_datetime
    field :sla_warning_sent_at, :utc_datetime

    belongs_to :organization, Codefresh.Organizations.Organization
    belongs_to :freeball_node, Codefresh.Runs.FreeballNode
    belongs_to :assigned_to_user, Codefresh.Accounts.User, foreign_key: :assigned_to_user_id

    timestamps(type: :utc_datetime)
  end

  def statuses, do: @statuses

  def create_changeset(item, attrs) do
    item
    |> cast(attrs, [
      :organization_id,
      :freeball_node_id,
      :status,
      :priority,
      :assigned_to_user_id,
      :claimed_at,
      :resolved_at,
      :resolution_notes,
      :assigned_at,
      :sla_warning_sent_at
    ])
    |> validate_required([:organization_id, :freeball_node_id])
    |> validate_inclusion(:status, @statuses)
    |> unique_constraint(:freeball_node_id)
    |> foreign_key_constraint(:organization_id)
    |> foreign_key_constraint(:freeball_node_id)
    |> foreign_key_constraint(:assigned_to_user_id)
  end

  def update_changeset(item, attrs) do
    item
    |> cast(attrs, [
      :status,
      :priority,
      :assigned_to_user_id,
      :claimed_at,
      :resolved_at,
      :resolution_notes,
      :assigned_at,
      :sla_warning_sent_at
    ])
    |> validate_inclusion(:status, @statuses)
  end
end
