{{- if .Values.secrets.infisical }}
{{- if .Values.secrets.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-{{ include "start-app.fullname" . }}-secrets
  labels:
    {{- include "start-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.secrets.infisical.hostAPI }}
  hostAPI: {{ .Values.secrets.infisical.hostAPI }}
  {{- end }}
  resyncInterval: {{ .Values.secrets.infisical.resyncInterval | default 120 }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.secrets.infisical.credentialsSecret | default "universal-auth-credentials" }}
        secretNamespace: {{ .Values.secrets.infisical.credentialsNamespace | default "infra" }}
      secretsScope:
        projectSlug: {{ .Values.secrets.infisical.projectSlug | default "k8-infra" }}
        envSlug: {{ .Values.secrets.infisical.envSlug | default "prod" }}
        secretsPath: {{ .Values.secrets.infisical.secretsPath | quote }}
  managedSecretReference:
    secretName: {{ .Values.secrets.name }}
    secretNamespace: {{ .Release.Namespace }}
    secretType: Opaque
    creationPolicy: Owner
    template:
      includeAllSecrets: true
{{- end }}
{{- end }}
