{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "start-app.fullname" . }}-migrate
  labels:
    {{- include "start-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "start-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: migrate
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        command: {{ .Values.migrate.command | toJson }}
        env:
          {{- include "start-app.backendEnv" . | nindent 8 }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- if .Values.configMap.enabled }}
        envFrom:
        - configMapRef:
            name: {{ include "start-app.fullname" . }}-config
        {{- end }}
        resources:
          {{- toYaml .Values.migrate.resources | nindent 10 }}
{{- end }}
