apiVersion: v1
kind: Service
metadata:
  name: {{ include "start-app.fullname" . }}
  labels:
    {{- include "start-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: backend
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
    protocol: TCP
  - name: frontend
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
  selector:
    {{- include "start-app.selectorLabels" . | nindent 4 }}
