apiVersion: v2
name: static-site
description: "Reusable nginx static-site deployment"
version: 0.1.0
appVersion: "0.1.0"
type: application
keywords:
  - static-site
  - nginx
maintainers:
  - name: Keith Brings
    email: keith.brings@noizu.com
