apiVersion: v1
kind: Service
metadata:
  name: {{ include "derobotis.fullname" . }}
  labels:
    {{- include "derobotis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.teaser.port }}
    targetPort: {{ .Values.teaser.port }}
    protocol: TCP
  selector:
    {{- include "derobotis.selectorLabels" . | nindent 4 }}
