SUBDIRS := k8-lib cluster-utils docker-utils helm-utils infra-utils secret-utils staging-utils
SUBDIR_PREFIX := k8/
SUBDIR_DESCRIPTION := Kubernetes utilities - clusters, Docker, Helm, staging and secrets

include ../mk/subdirs.mk
