static-site:
  nameOverride: therobotknows
  fullnameOverride: therobotknows
  domain: therobotknows.com
  image: ops.noizu.com/app-knowledge-base:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: therobotknows-com-tls

