apiVersion: v2
name: therobotmakes
description: "therobotmakes.com static website"
version: 0.1.0
appVersion: "0.1.0"
type: application
dependencies:
  - name: static-site
    version: 0.1.0
    repository: file://../../../../components/static-site/helm/static-site
