static-site:
  nameOverride: therobotmakes
  fullnameOverride: therobotmakes
  domain: therobotmakes.com
  image: ops.noizu.com/noizu-ink-landing:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: therobotmakes-com-tls

