package datasource

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/signoz/internal/attr"
	"github.com/SigNoz/terraform-provider-signoz/signoz/internal/client"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &dashboardDataSource{}
	_ datasource.DataSourceWithConfigure = &dashboardDataSource{}
)

// NewDashboardDataSource is a helper function to simplify the provider implementation.
func NewDashboardDataSource() datasource.DataSource {
	return &dashboardDataSource{}
}

// dashboardDataSource is the data source implementation.
type dashboardDataSource struct {
	client *client.Client
}

// dashboardModel maps dashboard schema data.
type dashboardModel struct {
	CollapsableRowsMigrated types.Bool   `tfsdk:"collapsable_rows_migrated"`
	Description             types.String `tfsdk:"description"`
	ID                      types.String `tfsdk:"id"`
	Layout                  types.String `tfsdk:"layout"`
	Name                    types.String `tfsdk:"name"`
	PanelMap                types.String `tfsdk:"panel_map"`
	Source                  types.String `tfsdk:"source"`
	Tags                    types.List   `tfsdk:"tags"`
	Title                   types.String `tfsdk:"title"`
	UploadedGrafana         types.Bool   `tfsdk:"uploaded_grafana"`
	Variables               types.String `tfsdk:"variables"`
	Version                 types.String `tfsdk:"version"`
	Widgets                 types.String `tfsdk:"widgets"`
}

// Metadata returns the data source type name.
func (d *dashboardDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = SigNozDashboard
}

// Configure adds the provider configured client to the data source.
func (d *dashboardDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Add a nil check when handling ProviderData because Terraform.
	// sets that data after it calls the ConfigureProvider RPC.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		addErr(
			&resp.Diagnostics,
			fmt.Errorf("unexpected data source configure type. Expected *client.Client, got: %T. "+
				"Please report this issue to the provider developers", req.ProviderData),
			SigNozDashboard,
		)

		return
	}

	d.client = client
}

// Schema defines the schema for the data source.
func (d *dashboardDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a dashboard from Signoz using its id. The id can be found in the URL of the dashboard in the Signoz UI.",
		Attributes: map[string]schema.Attribute{
			attr.CollapsableRowsMigrated: schema.BoolAttribute{
				Computed: true,
			},
			attr.Description: schema.StringAttribute{
				Computed:    true,
				Description: "Description of the dashboard.",
			},
			attr.ID: schema.StringAttribute{
				Required:    true,
				Description: "Autogenerated unique ID for the dashboard.",
			},
			attr.Layout: schema.StringAttribute{
				Computed:    true,
				Description: "Layout of the dashboard.",
			},
			attr.Name: schema.StringAttribute{
				Computed:    true,
				Description: "Name of the dashboard.",
			},
			attr.PanelMap: schema.StringAttribute{
				Computed: true,
			},
			attr.Source: schema.StringAttribute{
				Computed:    true,
				Description: "Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.",
			},
			attr.Tags: schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: "Tags of the dashboard.",
			},
			attr.Title: schema.StringAttribute{
				Computed:    true,
				Description: "Title of the dashboard.",
			},
			attr.UploadedGrafana: schema.BoolAttribute{
				Computed: true,
			},
			attr.Variables: schema.StringAttribute{
				Computed:    true,
				Description: "Variables for the dashboard.",
			},
			attr.Widgets: schema.StringAttribute{
				Computed:    true,
				Description: "Widgets for the dashboard.",
			},
			attr.Version: schema.StringAttribute{
				Computed: true,
				Optional: true,
			},
		},
	}
}

// Read refreshes the Terraform state with the latest data.
func (d *dashboardDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data dashboardModel
	var diags diag.Diagnostics

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	dashboard, err := d.client.GetDashboard(ctx, data.ID.ValueString())
	if err != nil {
		addErr(&resp.Diagnostics, fmt.Errorf("unable to read SigNoz dashboard: %s", err.Error()), SigNozDashboard)
		return
	}

	// Set state values from retrieved data.
	data.ID = types.StringValue(dashboard.ID)
	data.CollapsableRowsMigrated = types.BoolValue(dashboard.Data.CollapsableRowsMigrated)
	data.Description = types.StringValue(dashboard.Data.Description)
	data.Name = types.StringValue(dashboard.Data.Name)
	data.Title = types.StringValue(dashboard.Data.Title)
	data.UploadedGrafana = types.BoolValue(dashboard.Data.UploadedGrafana)
	data.Version = types.StringValue(dashboard.Data.Version)
	data.Source = types.StringValue(dashboard.Data.Source)
	// data.CreatedAt = types.StringValue(dashboard.CreatedAt)
	// data.CreatedBy = types.StringValue(dashboard.CreatedBy)
	// data.UpdatedAt = types.StringValue(dashboard.UpdatedAt)
	// data.UpdatedBy = types.StringValue(dashboard.UpdatedBy)

	data.PanelMap, err = dashboard.Data.PanelMapToTerraform()
	if err != nil {
		addErr(&resp.Diagnostics, err, operationRead)
		return
	}

	data.Variables, err = dashboard.Data.VariablesToTerraform()
	if err != nil {
		addErr(&resp.Diagnostics, err, operationRead)
		return
	}

	data.Layout, err = dashboard.Data.LayoutToTerraform()
	if err != nil {
		addErr(&resp.Diagnostics, err, operationRead)
		return
	}

	data.Widgets, err = dashboard.Data.WidgetsToTerraform()
	if err != nil {
		addErr(&resp.Diagnostics, err, operationRead)
		return
	}

	data.Tags, diags = dashboard.Data.TagsToTerraform()
	resp.Diagnostics.Append(diags...)

	// Set state.
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
