apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "static-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-site.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: web
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
