{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- if .Values.ingress.cloudflareOnly }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "static-site.cloudflareWhitelist" . | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "static-site.fullname" . }}
            port:
              number: {{ .Values.port }}
{{- end }}
