apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    {{- include "static-site.selectorLabels" . | nindent 4 }}
