#!/usr/bin/env python3
"""Generate individual user story files for therobotbrowses."""

import os

STORIES_DIR = os.path.join(os.path.dirname(__file__), "stories")
os.makedirs(STORIES_DIR, exist_ok=True)

PERSONAS = {
    "P-001": ("Kai Nakamura", "tool-building developer"),
    "P-002": ("Dr. Amara Osei", "researcher"),
    "P-003": ("Maya Johansson", "keyboard power user"),
    "P-004": ("Jordan Rivera", "accessibility advocate"),
    "P-005": ("Suki Tanaka", "security analyst"),
    "A-001": ("Claude", "browsing copilot agent"),
    "A-002": ("Crawler", "headless data harvester agent"),
    "A-003": ("Sentinel", "security/privacy monitor agent"),
    "A-004": ("Weaver", "workflow automator agent"),
}

PHASES = {
    0: ("Shell", "Navigate and display raw HTML in TUI"),
    1: ("Render", "ACID1 pass"),
    2: ("Paint", "Visual web pages"),
    3: ("Interact", "Interactive pages"),
    4: ("Connect", "Full MCP tool surface"),
    5: ("Extend", "User-installable extensions"),
    6: ("Comply", "Standards compliance"),
    7: ("Ship", "Public alpha"),
}

stories = [
    # Phase 0 — Shell
    {"id": "US-001", "title": "Navigate to a URL", "phase": 0, "priority": "P0",
     "personas": ["P-001", "P-003"],
     "as": "P-001", "want": "to type a URL into an input bar and press Enter to issue an HTTP/HTTPS request",
     "so_that": "I can fetch and view web content without leaving the terminal",
     "ac": [
         "URL bar accepts text input and submits on Enter",
         "HTTP and HTTPS schemes are supported; bare domains default to `https://`",
         "The fetched response body is displayed in the content pane",
         "Invalid URLs produce a clear inline error (not a crash)",
     ],
     "standards": ["WHATWG URL Standard", "RFC 9110 (HTTP Semantics)", "RFC 8446 (TLS 1.3)"]},

    {"id": "US-002", "title": "Display Raw HTML", "phase": 0, "priority": "P0",
     "personas": ["P-002", "P-001"],
     "as": "P-002", "want": "the fetched HTML source displayed verbatim in the content pane",
     "so_that": "I can inspect page structure before any rendering engine exists",
     "ac": [
         "Raw HTML is displayed with preserved whitespace and indentation",
         "Content pane is scrollable (vertical at minimum)",
         "Large documents (>1 MB) load without freezing the TUI",
         "UTF-8 content renders correctly; other charsets show a warning",
     ],
     "standards": ["WHATWG Encoding Standard", "ISO/IEC 10646 (Unicode)"]},

    {"id": "US-003", "title": "Open a New Tab", "phase": 0, "priority": "P0",
     "personas": ["P-003", "P-001"],
     "as": "P-003", "want": "to open a new tab with a keybinding",
     "so_that": "I can have multiple pages loaded simultaneously without losing context",
     "ac": [
         "A keybinding (default: `Ctrl+T`) opens a new empty tab with focus on the URL bar",
         "Tab bar updates immediately to show the new tab",
         "New tabs are appended to the right of the current tab",
         "Tab count is displayed somewhere visible (tab bar or status line)",
     ],
     "standards": ["WCAG 2.2 SC 2.1.1 (Keyboard)", "EN 301 549 §11.2.1.1"]},

    {"id": "US-004", "title": "Close a Tab", "phase": 0, "priority": "P0",
     "personas": ["P-003", "P-001"],
     "as": "P-003", "want": "to close the current tab with a keybinding",
     "so_that": "I can dismiss pages I no longer need without reaching for a mouse",
     "ac": [
         "A keybinding (default: `Ctrl+W`) closes the active tab",
         "Focus moves to the next tab, or the previous tab if the closed tab was last",
         "Closing the last tab exits the browser (or opens a blank tab, configurable)",
         "No confirmation prompt for closing tabs in Phase 0",
     ],
     "standards": ["WCAG 2.2 SC 2.1.1 (Keyboard)"]},

    {"id": "US-005", "title": "Switch Between Tabs", "phase": 0, "priority": "P0",
     "personas": ["P-003", "A-001"],
     "as": "P-003", "want": "to switch between tabs using keyboard shortcuts",
     "so_that": "I can move fluidly between multiple pages",
     "ac": [
         "`Ctrl+Tab` / `Ctrl+Shift+Tab` cycle forward/backward through tabs",
         "`Alt+1` through `Alt+9` jump to tab by position (1-indexed)",
         "Active tab is visually highlighted in the tab bar",
         "Switching tabs restores scroll position of the destination tab",
     ],
     "standards": ["WCAG 2.2 SC 2.4.3 (Focus Order)"]},

    {"id": "US-006", "title": "List All Open Tabs", "phase": 0, "priority": "P1",
     "personas": ["A-001", "P-003", "P-001"],
     "as": "A-001", "want": "to retrieve a list of all open tabs with their URLs and titles",
     "so_that": "I can reason about what the user has open and suggest relevant actions",
     "ac": [
         "A command or keybinding displays a tab list overlay (index, URL, title/status)",
         "The list is navigable and selecting an entry switches to that tab",
         "The same data is available programmatically via MCP `tabs/list` tool",
         "Tabs are ordered by position, not most-recently-used",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-007", "title": "Inspect Response Headers and Status Code", "phase": 0, "priority": "P0",
     "personas": ["P-005", "P-001", "A-003"],
     "as": "P-005", "want": "to view the HTTP response status code, headers, and timing for the current page",
     "so_that": "I can audit server behavior, caching policy, and security headers",
     "ac": [
         "A toggleable inspector pane shows: status code, reason phrase, all response headers",
         "Request timing is displayed (DNS, connect, TLS handshake, TTFB, total)",
         "Headers are displayed as `Name: Value` pairs, preserving original casing",
         "Inspector pane can be opened with a keybinding (default: `F12` or `Ctrl+I`)",
     ],
     "standards": ["RFC 9110 (HTTP Semantics)", "RFC 9112 (HTTP/1.1)"]},

    {"id": "US-008", "title": "Inspect Request Details", "phase": 0, "priority": "P1",
     "personas": ["P-005", "P-001"],
     "as": "P-005", "want": "to view the outgoing HTTP request (method, URL, headers sent)",
     "so_that": "I can verify what the browser transmitted and debug request issues",
     "ac": [
         "The inspector pane includes a Request section showing method, URL, and all sent headers",
         "User-Agent and other auto-injected headers are visible",
         "Request and response sections are independently scrollable",
         "Copy-to-clipboard works for individual headers or the full request block",
     ],
     "standards": ["RFC 9110 (HTTP Semantics)"]},

    {"id": "US-009", "title": "Handle DNS Failures Gracefully", "phase": 0, "priority": "P0",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "DNS resolution failures to produce a clear, readable error page in the content pane",
     "so_that": "I understand what went wrong without deciphering a stack trace",
     "ac": [
         "DNS failures display an error page with: the failing domain, error type, and a suggestion",
         "The error page is navigable (URL bar remains editable for retry)",
         "Screen readers can parse the error content (plain text, no raw ANSI artifacts)",
         "The tab title updates to reflect the error state (e.g., 'Error — example.invalid')",
     ],
     "standards": ["RFC 1035 (DNS)", "WCAG 2.2 SC 4.1.3 (Status Messages)", "EN 301 549 §11.4.1.3"]},

    {"id": "US-010", "title": "Handle Connection Timeouts", "phase": 0, "priority": "P1",
     "personas": ["P-001", "A-002"],
     "as": "P-001", "want": "connection and read timeouts to be configurable and to surface clearly",
     "so_that": "I can diagnose slow or unresponsive servers",
     "ac": [
         "Default connect timeout: 10 seconds; default read timeout: 30 seconds",
         "Timeouts are configurable via config file",
         "Timeout errors display elapsed time and which phase timed out (connect vs. read)",
         "A loading indicator is visible while a request is in-flight",
     ],
     "standards": ["RFC 9110 (HTTP Semantics)"]},

    {"id": "US-011", "title": "Handle TLS Errors", "phase": 0, "priority": "P1",
     "personas": ["P-005", "A-003"],
     "as": "P-005", "want": "TLS certificate errors to be clearly reported with details (expiry, CN mismatch, self-signed)",
     "so_that": "I can assess the risk before deciding whether to proceed",
     "ac": [
         "TLS errors display: error type, certificate subject, issuer, expiry date",
         "The user is not silently redirected or allowed to proceed without acknowledgment",
         "A `--insecure` flag or config option exists for development use (disabled by default)",
         "TLS error details are available in the inspector pane",
     ],
     "standards": ["RFC 8446 (TLS 1.3)", "RFC 5280 (X.509)", "RFC 6962 (Certificate Transparency)"]},

    {"id": "US-012", "title": "Follow Redirects", "phase": 0, "priority": "P1",
     "personas": ["A-002", "P-001"],
     "as": "A-002", "want": "HTTP redirects (301, 302, 307, 308) to be followed automatically up to a configurable limit",
     "so_that": "I reach final destinations without manual intervention",
     "ac": [
         "Redirects are followed automatically (default limit: 10 hops)",
         "The URL bar updates to the final URL after redirects",
         "The inspector pane shows the full redirect chain (each hop with status and Location header)",
         "Redirect limit is configurable; exceeding it produces a clear error",
     ],
     "standards": ["RFC 9110 §15.4 (Redirection)", "WHATWG Fetch Standard"]},

    {"id": "US-013", "title": "In-Session History", "phase": 0, "priority": "P1",
     "personas": ["P-003", "P-001"],
     "as": "P-003", "want": "back/forward navigation within a tab's session history",
     "so_that": "I can retrace my steps without re-typing URLs",
     "ac": [
         "`Alt+Left` / `Alt+Right` (or configurable) navigate back/forward in per-tab history",
         "History stack tracks URLs visited within a tab during the current session",
         "Back/forward buttons are visually indicated as enabled/disabled in the status line",
         "History is per-tab and not persisted across sessions in Phase 0",
     ],
     "standards": ["HTML Living Standard (History API)"]},

    {"id": "US-014", "title": "Keyboard-Driven Focus Management", "phase": 0, "priority": "P0",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "clear, predictable keyboard focus cycling between the URL bar, tab bar, content pane, and inspector",
     "so_that": "I can operate the browser entirely without a pointing device",
     "ac": [
         "`Tab` / `Shift+Tab` cycle focus between major UI regions",
         "The focused region has a visible border or highlight indicator",
         "`Escape` returns focus to the content pane from any input field",
         "Focus order is logical: URL bar -> content pane -> inspector (if open)",
     ],
     "standards": ["WCAG 2.2 SC 2.1.1 (Keyboard)", "WCAG 2.2 SC 2.4.3 (Focus Order)", "WCAG 2.2 SC 2.4.7 (Focus Visible)", "WCAG 2.2 SC 2.4.11 (Focus Appearance)", "EN 301 549 §11.2.1.1"]},

    {"id": "US-015", "title": "Headless Mode (No TUI)", "phase": 0, "priority": "P1",
     "personas": ["A-002", "A-004", "P-001"],
     "as": "A-002", "want": "to start the browser in headless mode with no TUI rendering",
     "so_that": "I can drive it purely through MCP tools or CLI flags for automated data collection",
     "ac": [
         "`--headless` flag starts the browser without initializing the TUI",
         "In headless mode, navigation is driven via MCP tool calls or CLI subcommands",
         "stdout output is structured (JSON) for machine consumption",
         "Exit codes reflect success (0), navigation error (1), or argument error (2)",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-016", "title": "Basic MCP Server Startup", "phase": 0, "priority": "P1",
     "personas": ["A-001", "A-002", "A-004"],
     "as": "A-001", "want": "the browser to start an MCP server exposing navigation and page-content tools",
     "so_that": "I can programmatically navigate to URLs and read page source",
     "ac": [
         "`--mcp` flag starts an MCP server on stdio transport (default) or SSE (configurable)",
         "Minimum tool surface: `navigate`, `get_page_source`, `get_url`, `tabs/list`, `tabs/open`, `tabs/close`",
         "MCP server is available in both TUI and headless modes",
         "Tool responses use structured JSON with consistent error schemas",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-017", "title": "Configurable Keybindings", "phase": 0, "priority": "P2",
     "personas": ["P-003", "P-004"],
     "as": "P-003", "want": "to remap keybindings via a config file",
     "so_that": "I can match my muscle memory from other tools",
     "ac": [
         "Keybindings are defined in a TOML or YAML config file (e.g., `~/.config/therobotbrowses/keys.toml`)",
         "All default bindings are overridable",
         "Invalid key definitions produce a startup warning, not a crash",
         "A `--dump-keybindings` flag prints the active keymap to stdout",
     ],
     "standards": ["WCAG 2.2 SC 2.1.1 (Keyboard)"]},

    {"id": "US-018", "title": "Status Bar with Connection Info", "phase": 0, "priority": "P1",
     "personas": ["P-001", "P-003"],
     "as": "P-001", "want": "a persistent status bar showing connection state, current URL, and request status",
     "so_that": "I have ambient awareness of what the browser is doing",
     "ac": [
         "Status bar is always visible at the bottom of the TUI",
         "Displays: current URL (truncated if needed), HTTP status code, TLS lock indicator",
         "Shows a spinner or progress indicator during active requests",
         "Shows 'Disconnected' / 'Error' states distinctly from successful loads",
     ],
     "standards": ["WCAG 2.2 SC 4.1.3 (Status Messages)"]},

    {"id": "US-019", "title": "Reload Current Page", "phase": 0, "priority": "P1",
     "personas": ["P-002", "P-003"],
     "as": "P-002", "want": "to reload the current page with a keybinding",
     "so_that": "I can re-fetch content that may have changed without re-typing the URL",
     "ac": [
         "`F5` or `Ctrl+R` re-fetches the current URL",
         "Scroll position resets to top on reload",
         "The inspector pane updates with the new request/response data",
         "Reload is a no-op on empty tabs or error pages with no URL",
     ],
     "standards": ["RFC 9111 (HTTP Caching)"]},

    {"id": "US-020", "title": "Graceful Shutdown and Cleanup", "phase": 0, "priority": "P1",
     "personas": ["A-004", "A-002", "P-001"],
     "as": "A-004", "want": "the browser to shut down cleanly when receiving SIGINT/SIGTERM or when the last tab closes",
     "so_that": "I can orchestrate browser lifecycle in automated pipelines without orphaned processes",
     "ac": [
         "`Ctrl+C` or SIGTERM triggers graceful shutdown (close connections, flush state)",
         "MCP server sends clean shutdown notification to connected clients before exit",
         "No zombie processes or leaked file descriptors after exit",
         "Exit within 3 seconds of signal; force-kill after 5 seconds",
     ],
     "standards": ["POSIX Signal Handling"]},

    # Phase 1 — Render
    {"id": "US-100", "title": "HTML Parsing via html5ever", "phase": 1, "priority": "P0",
     "personas": ["P-001", "A-002"],
     "as": "P-001", "want": "the browser to parse HTML documents using html5ever",
     "so_that": "I get spec-compliant DOM construction without reinventing a parser",
     "ac": [
         "html5ever is integrated as the HTML tokenizer and tree builder",
         "Malformed HTML is handled according to the HTML5 error-recovery spec",
         "Parser produces a well-formed DOM tree for any valid HTML5 document",
         "Parse time for a 100KB document is under 50ms on release builds",
     ],
     "standards": ["WHATWG HTML Living Standard §12-13 (Parsing)", "ISO/IEC 15445:2000 (historical)"]},

    {"id": "US-101", "title": "DOM Tree Construction and Querying", "phase": 1, "priority": "P0",
     "personas": ["A-001", "A-002", "P-001"],
     "as": "A-001", "want": "a queryable DOM tree with standard traversal methods",
     "so_that": "I can locate elements by tag, id, class, or CSS selector",
     "ac": [
         "DOM nodes store tag name, attributes, text content, and parent/child/sibling references",
         "`querySelector` and `querySelectorAll` style lookups work against the tree",
         "DOM tree is immutable during layout to prevent data races",
         "Tree supports efficient subtree extraction for agent inspection",
     ],
     "standards": ["WHATWG DOM Living Standard", "CSS Selectors Level 3 (W3C REC)"]},

    {"id": "US-102", "title": "CSS Parsing", "phase": 1, "priority": "P0",
     "personas": ["P-001", "A-001"],
     "as": "P-001", "want": "the browser to parse CSS2.1 stylesheets into a structured rule set",
     "so_that": "styles can be resolved against the DOM",
     "ac": [
         "Inline `style` attributes, `<style>` blocks, and linked stylesheets are all parsed",
         "Selectors support type, class, ID, descendant, child, and universal combinators",
         "Property values are parsed into typed representations (lengths, colors, keywords)",
         "Malformed rules are skipped without crashing the parser",
     ],
     "standards": ["CSS 2.1 (W3C REC)", "CSS Syntax Level 3 (W3C CR)"]},

    {"id": "US-103", "title": "CSS Cascade and Specificity Resolution", "phase": 1, "priority": "P0",
     "personas": ["P-002", "P-001"],
     "as": "P-002", "want": "the browser to resolve conflicting CSS declarations using the standard cascade",
     "so_that": "pages render with correct visual priority",
     "ac": [
         "Cascade order is respected: user-agent < author < inline",
         "Specificity is computed correctly (id > class > type) with tie-breaking by source order",
         "`!important` declarations override normal declarations",
         "Inherited properties propagate from parent to child correctly",
     ],
     "standards": ["CSS Cascading and Inheritance Level 4 (W3C CR)"]},

    {"id": "US-104", "title": "CSS Computed and Used Value Resolution", "phase": 1, "priority": "P0",
     "personas": ["A-001", "P-001", "P-004"],
     "as": "A-001", "want": "every DOM element to have fully resolved computed styles",
     "so_that": "I can inspect the final visual properties of any element",
     "ac": [
         "Percentage values resolve against the containing block",
         "`em` and `rem` units resolve to absolute pixel values",
         "`inherit`, `initial`, and default values resolve correctly",
         "Computed styles are queryable per-element via internal API",
     ],
     "standards": ["CSS Values and Units Level 3 (W3C CR)", "CSSOM View (W3C WD)"]},

    {"id": "US-105", "title": "Box Model Computation", "phase": 1, "priority": "P0",
     "personas": ["P-001", "A-001"],
     "as": "P-001", "want": "each element to have computed margin, border, padding, and content dimensions",
     "so_that": "layout can position elements correctly",
     "ac": [
         "`margin`, `border-width`, `padding`, and `width`/`height` are computed per element",
         "`auto` margins resolve correctly for block-level centering",
         "`box-sizing: content-box` is the default; `border-box` adjusts width/height to include padding and border",
         "Negative margins are supported",
     ],
     "standards": ["CSS Box Model Level 3 (W3C CR)", "Acid1 (CSS1 box model validation)"]},

    {"id": "US-106", "title": "Block Layout", "phase": 1, "priority": "P0",
     "personas": ["P-002", "P-001"],
     "as": "P-002", "want": "block-level elements to stack vertically with correct margin collapsing",
     "so_that": "document flow renders as expected",
     "ac": [
         "Block boxes are laid out top-to-bottom within their containing block",
         "Vertical margins between adjacent siblings collapse to the larger value",
         "`width: auto` expands to fill the containing block",
         "`height: auto` shrinks to fit content",
     ],
     "standards": ["CSS 2.1 §8.3.1 (Collapsing Margins)", "CSS Display Level 3 (W3C CR)"]},

    {"id": "US-107", "title": "Inline Layout and Text Wrapping", "phase": 1, "priority": "P0",
     "personas": ["P-003", "P-002", "A-001"],
     "as": "P-003", "want": "inline text to wrap at word boundaries within its container",
     "so_that": "paragraphs are readable without horizontal scrolling",
     "ac": [
         "Inline boxes flow left-to-right, wrapping to the next line when the line box is full",
         "Line height is computed from `line-height` and font metrics",
         "White space collapsing follows CSS `white-space: normal` rules",
         "`<br>` forces a line break",
     ],
     "standards": ["CSS Text Level 3 (W3C CR)", "CSS 2.1 §9.4.2 (Inline formatting)", "Unicode UAX#14 (Line Breaking)"]},

    {"id": "US-108", "title": "Font Loading and Text Rendering (System Fonts)", "phase": 1, "priority": "P0",
     "personas": ["P-003", "P-004", "A-001"],
     "as": "P-003", "want": "text rendered using system fonts with correct glyph selection",
     "so_that": "content is legible on screen",
     "ac": [
         "System font families (serif, sans-serif, monospace) are resolved to platform fonts",
         "`font-size`, `font-weight`, `font-style` are respected in glyph selection",
         "Text is rasterized at the correct size and position within line boxes",
         "Missing glyphs fall back to a tofu/replacement character rather than crashing",
     ],
     "standards": ["CSS Fonts Level 4 (W3C CR)", "ISO/IEC 10646 (Unicode)", "OpenType spec (ISO/IEC 14496-22)"]},

    {"id": "US-109", "title": "Color and Background Rendering", "phase": 1, "priority": "P0",
     "personas": ["P-002", "P-004"],
     "as": "P-002", "want": "elements to render with correct foreground and background colors",
     "so_that": "visual hierarchy and readability are preserved",
     "ac": [
         "`color` property applies to text rendering",
         "`background-color` fills the padding box of each element",
         "Named colors, hex (`#rgb`, `#rrggbb`), and `rgb()` notation are supported",
         "Transparent backgrounds show the parent's background through",
     ],
     "standards": ["CSS Color Level 4 (W3C CR)"]},

    {"id": "US-110", "title": "List Styling (Bullets and Numbers)", "phase": 1, "priority": "P1",
     "personas": ["A-002", "P-002"],
     "as": "A-002", "want": "ordered and unordered lists to render with correct markers",
     "so_that": "list semantics are visually represented and structurally parseable",
     "ac": [
         "`<ul>` renders disc markers by default",
         "`<ol>` renders decimal numbers starting from 1 (or the `start` attribute)",
         "`list-style-type: none` suppresses markers",
         "List item content indents correctly from the marker",
     ],
     "standards": ["CSS Lists Level 3 (W3C CR)", "CSS Counter Styles Level 3 (W3C CR)"]},

    {"id": "US-111", "title": "Basic Table Layout", "phase": 1, "priority": "P1",
     "personas": ["P-002", "A-002"],
     "as": "P-002", "want": "HTML tables to render with rows, columns, and cell alignment",
     "so_that": "tabular data is presented readably",
     "ac": [
         "`<table>`, `<tr>`, `<td>`, `<th>` elements produce a grid layout",
         "Column widths distribute based on content (auto table layout algorithm)",
         "`border`, `cellpadding`, and `cellspacing` attributes are respected",
         "Cells spanning multiple columns (`colspan`) are handled correctly",
     ],
     "standards": ["CSS Table Level 3 (W3C WD)", "Acid1 (table layout validation)"]},

    {"id": "US-112", "title": "Image Placeholders", "phase": 1, "priority": "P1",
     "personas": ["A-001", "A-002", "P-001"],
     "as": "A-001", "want": "images with known dimensions to reserve the correct space in layout",
     "so_that": "page geometry is stable even before image data loads",
     "ac": [
         "`<img>` with `width` and `height` attributes reserves a box of that size",
         "A visible placeholder (gray box or outline) renders in place of the image",
         "`alt` text renders inside the placeholder when present",
         "Missing dimensions fall back to a default placeholder size (e.g., 300x150)",
     ],
     "standards": ["HTML Living Standard (§4.8.3 img element)", "WCAG 2.2 SC 1.1.1 (Non-text Content)"]},

    {"id": "US-113", "title": "Layout Tree Inspection via MCP", "phase": 1, "priority": "P1",
     "personas": ["A-001", "A-003", "A-004"],
     "as": "A-001", "want": "to query the layout tree through an MCP tool interface",
     "so_that": "I can read computed styles, box dimensions, and element positions programmatically",
     "ac": [
         "MCP tool `inspect_element(selector)` returns computed styles and box geometry for matched elements",
         "MCP tool `layout_tree()` returns a serialized tree with tag, position, and dimensions per node",
         "MCP tool `computed_style(selector, property)` returns the resolved value of a specific CSS property",
         "All MCP responses use JSON with consistent schema",
     ],
     "standards": ["MCP Protocol Specification", "CSSOM View (W3C WD)"]},

    {"id": "US-114", "title": "Accessibility Tree Generation from DOM", "phase": 1, "priority": "P1",
     "personas": ["P-004", "A-001", "A-003"],
     "as": "P-004", "want": "the browser to build an accessibility tree from the DOM",
     "so_that": "screen readers and agent tools can consume semantic structure",
     "ac": [
         "Semantic elements (`<h1>`-`<h6>`, `<nav>`, `<main>`, `<article>`, `<button>`) map to correct accessibility roles",
         "`alt` text on images is exposed as the accessible name",
         "`aria-label` and `aria-role` attributes override default semantics",
         "The accessibility tree is queryable independently from the layout tree",
     ],
     "standards": ["WAI-ARIA 1.2 (W3C REC)", "HTML-AAM 1.0 (W3C CR)", "Core-AAM 1.2 (W3C REC)", "ISO/IEC 40500:2025 (WCAG 2.2)"]},

    {"id": "US-115", "title": "Viewport Sizing", "phase": 1, "priority": "P1",
     "personas": ["P-003", "A-002", "P-001"],
     "as": "P-003", "want": "to set the viewport dimensions and have the layout reflow accordingly",
     "so_that": "I can view pages at any window size",
     "ac": [
         "Layout uses the viewport width as the initial containing block width",
         "Changing viewport size triggers a full relayout",
         "Viewport height establishes the visible area for scroll calculations",
         "Default viewport is configurable (e.g., 1024x768 for headless, window size for GUI)",
     ],
     "standards": ["CSS 2.1 §9.1.2 (Containing blocks)", "CSS Media Queries Level 4"]},

    {"id": "US-116", "title": "Vertical Scrolling", "phase": 1, "priority": "P1",
     "personas": ["P-003", "A-001"],
     "as": "P-003", "want": "content taller than the viewport to be scrollable",
     "so_that": "I can access the full document",
     "ac": [
         "Document height is computed from the layout tree",
         "Scroll offset shifts the rendered view without relayout",
         "Scroll position is queryable (for agents and keyboard navigation)",
         "`overflow: hidden` on an element clips its content and disables scrolling for that box",
     ],
     "standards": ["CSS Overflow Level 3 (W3C CR)", "CSSOM View (W3C WD)"]},

    {"id": "US-117", "title": "ACID1 Test Compliance", "phase": 1, "priority": "P0",
     "personas": ["P-001", "P-002"],
     "as": "P-001", "want": "the browser to pass the ACID1 test",
     "so_that": "I have a baseline confidence that core CSS and layout are correct",
     "ac": [
         "The ACID1 reference page renders without visual defects when compared to the reference image",
         "All box model, color, and positioning rules exercised by ACID1 produce correct output",
         "An automated pixel-diff test confirms < 1% deviation from the reference rendering",
         "The test runs in CI and blocks merges on failure",
     ],
     "standards": ["CSS Level 1 (W3C REC)", "Acid1 Test Suite (W3C CSS1 test 5.5.26.c)", "Web Platform Tests (css/css2/)"]},

    {"id": "US-118", "title": "Agent-Queryable DOM Snapshot via MCP", "phase": 1, "priority": "P1",
     "personas": ["A-002", "A-004", "A-001"],
     "as": "A-002", "want": "to retrieve a full DOM snapshot through MCP",
     "so_that": "I can extract structured data without rendering",
     "ac": [
         "MCP tool `dom_snapshot()` returns the full DOM as a serialized tree (JSON)",
         "Each node includes tag, attributes, text content, and child references",
         "Snapshot includes document metadata (title, base URL, encoding)",
         "Snapshot generation completes in under 100ms for typical pages",
     ],
     "standards": ["WHATWG DOM Living Standard", "MCP Protocol Specification"]},

    {"id": "US-119", "title": "Security Boundary — Style Isolation", "phase": 1, "priority": "P1",
     "personas": ["A-003", "P-005"],
     "as": "A-003", "want": "CSS parsing to reject resource loads and executable content",
     "so_that": "the style layer cannot be used as an attack vector",
     "ac": [
         "CSS `url()` references are parsed but not fetched during Phase 1 (logged as deferred)",
         "`expression()` and `-moz-binding` are rejected during parsing",
         "No external resource is fetched without explicit approval from the resource policy",
         "CSS parse errors are logged with source location for audit",
     ],
     "standards": ["CSP Level 3 (style-src directive)", "CSS Syntax Level 3 (error handling)"]},

    # Phase 2 — Paint
    {"id": "US-201", "title": "GPU Rendering Pipeline Initialization", "phase": 2, "priority": "P0",
     "personas": ["P-001", "P-003"],
     "as": "P-001", "want": "the browser to initialize a wgpu-based GPU rendering pipeline on startup",
     "so_that": "all visual output is hardware-accelerated and I can build on a performant foundation",
     "ac": [
         "wgpu adapter and device are acquired with graceful fallback to software rasterizer",
         "A render surface is created and bound to the native window",
         "Frame presentation uses double-buffering with vsync",
         "GPU initialization errors produce actionable diagnostics to stderr",
     ],
     "standards": ["WebGPU (W3C CR)", "Vulkan/Metal/DX12 backend abstraction"]},

    {"id": "US-202", "title": "Box Model Painting", "phase": 2, "priority": "P0",
     "personas": ["P-003", "P-004"],
     "as": "P-003", "want": "the browser to paint CSS box model elements (backgrounds, borders, padding) correctly",
     "so_that": "pages render with proper visual structure",
     "ac": [
         "Background colors and background-clip are painted per CSS spec",
         "Border widths, styles (solid, dashed, dotted, double), and colors render correctly",
         "Border-radius produces anti-aliased rounded corners",
         "Box-shadow (inset and outset) renders with correct blur and spread",
     ],
     "standards": ["CSS Backgrounds and Borders Level 3 (W3C CR)", "Acid2 (CSS2 box model painting)"]},

    {"id": "US-203", "title": "Image Decoding and Display", "phase": 2, "priority": "P0",
     "personas": ["P-002", "A-002"],
     "as": "P-002", "want": "the browser to decode and display PNG, JPEG, GIF, and WebP images",
     "so_that": "I can view research papers, diagrams, and figures inline",
     "ac": [
         "PNG images decode with alpha transparency support",
         "JPEG images decode with proper color space conversion (CMYK to sRGB)",
         "GIF images decode with first-frame display (animated GIF support is P2)",
         "WebP images decode (lossy and lossless)",
         "Broken or unsupported images display a placeholder with alt text",
         "Image decoding runs on a background thread to avoid blocking paint",
     ],
     "standards": ["ISO 15948 (PNG)", "ISO/IEC 10918 (JPEG)", "WebP (Google)", "Acid2 (PNG alpha transparency)"]},

    {"id": "US-204", "title": "Font Rendering with Hinting and Antialiasing", "phase": 2, "priority": "P0",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "text to render with proper font hinting, subpixel antialiasing, and configurable sizing",
     "so_that": "text is legible at all sizes and display densities",
     "ac": [
         "System fonts are discovered and loaded via fontdb or equivalent",
         "TrueType and OpenType font rendering with hinting (light, normal, full modes)",
         "Subpixel antialiasing for LCD displays, with grayscale fallback",
         "Font fallback chain resolves missing glyphs across installed fonts",
         "Emoji rendering via color font tables (COLR/CPAL or CBDT/CBLC)",
         "Minimum font size is configurable (accessibility setting)",
     ],
     "standards": ["OpenType spec (ISO/IEC 14496-22)", "CSS Fonts Level 4 (W3C CR)", "WCAG 2.2 SC 1.4.4 (Resize Text)"]},

    {"id": "US-205", "title": "CSS Gradient Rendering", "phase": 2, "priority": "P1",
     "personas": ["P-001", "P-003"],
     "as": "P-001", "want": "the browser to render CSS linear, radial, and conic gradients",
     "so_that": "modern web pages display correctly without visual regressions",
     "ac": [
         "Linear gradients render with correct angle, color stops, and interpolation",
         "Radial gradients render (circle and ellipse shapes, closest-side/farthest-corner sizing)",
         "Conic gradients render with correct from-angle and color stop distribution",
         "Repeating variants of all three gradient types work",
         "Gradient rendering is performed on the GPU via shader programs",
     ],
     "standards": ["CSS Images Level 3 (W3C CR)"]},

    {"id": "US-206", "title": "Compositing and Z-Order", "phase": 2, "priority": "P0",
     "personas": ["A-001", "P-001"],
     "as": "A-001", "want": "overlapping elements to composite correctly according to CSS stacking contexts and z-index",
     "so_that": "I can reliably identify which elements are visually on top when interpreting a page",
     "ac": [
         "Stacking contexts are created per CSS spec (position, opacity, transform, etc.)",
         "z-index ordering is respected within each stacking context",
         "opacity < 1.0 composites correctly with elements underneath",
         "mix-blend-mode applies (at minimum: normal, multiply, screen, overlay)",
         "Overflow clipping (overflow: hidden/scroll/auto) clips child content correctly",
     ],
     "standards": ["CSS 2.1 Appendix E (Stacking)", "CSS Compositing and Blending Level 1"]},

    {"id": "US-207", "title": "Smooth Scrolling and Scroll Snap", "phase": 2, "priority": "P1",
     "personas": ["P-003", "P-004"],
     "as": "P-003", "want": "pages to scroll smoothly via keyboard, trackpad, and mouse wheel, with CSS scroll-snap support",
     "so_that": "navigation feels responsive and precise",
     "ac": [
         "Scroll events from mouse wheel, trackpad gesture, and keyboard produce smooth animation",
         "scroll-behavior: smooth animates scroll position over time",
         "CSS scroll-snap-type (x/y, mandatory/proximity) snaps to scroll-snap-align targets",
         "Scrollbar is rendered (native or custom) and is draggable",
         "Overflow: auto/scroll creates scrollable containers for overflowing content",
         "Scroll position is maintained on back/forward navigation",
     ],
     "standards": ["CSS Scroll Snap Level 1 (W3C CR)", "CSS Overflow Level 3 (W3C CR)"]},

    {"id": "US-208", "title": "Text Selection and Highlighting", "phase": 2, "priority": "P1",
     "personas": ["P-002", "P-003", "A-001"],
     "as": "P-002", "want": "to select text by clicking and dragging, and see it highlighted",
     "so_that": "I can copy content from web pages for my research",
     "ac": [
         "Click-and-drag selects text across inline elements",
         "Double-click selects a word; triple-click selects a line/paragraph",
         "Selection is visually highlighted with the system selection color",
         "Ctrl/Cmd+A selects all text in the document",
         "Selected text is available to the clipboard on Ctrl/Cmd+C",
     ],
     "standards": ["CSSOM View (W3C WD)", "Selection API", "Clipboard API (W3C WD)"]},

    {"id": "US-209", "title": "HiDPI and Multi-Monitor Support", "phase": 2, "priority": "P1",
     "personas": ["P-001", "P-003"],
     "as": "P-001", "want": "the browser to render correctly on HiDPI (Retina) displays and handle monitor scale factor changes",
     "so_that": "content is crisp regardless of display configuration",
     "ac": [
         "Device pixel ratio is detected and applied to the render surface",
         "Moving the window between monitors with different scale factors triggers re-render at the correct DPI",
         "Images are rendered at native resolution when available (srcset support is Phase 3+)",
         "Text remains crisp at all scale factors",
     ],
     "standards": ["CSS Media Queries Level 4 (resolution)", "CSSOM View (devicePixelRatio)"]},

    {"id": "US-210", "title": "Accessibility Paint Modes", "phase": 2, "priority": "P1",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "the browser to support forced-colors mode and high-contrast rendering",
     "so_that": "users with visual impairments can perceive all page content",
     "ac": [
         "forced-colors: active media query is detectable and applies system color overrides",
         "prefers-contrast: more/less media query is reported to CSS",
         "A built-in high-contrast toggle overrides page colors with a user-selected palette",
         "Focus indicators are always visible (minimum 2px solid outline) regardless of page styles",
         "Text-over-image areas compute contrast and optionally add a background scrim",
     ],
     "standards": ["CSS Color Adjust Level 1 (forced-colors)", "WCAG 2.2 SC 1.4.11 (Non-text Contrast)", "EN 301 549 §11.7 (User preferences)"]},

    {"id": "US-211", "title": "Paint Performance Profiling", "phase": 2, "priority": "P2",
     "personas": ["A-002", "P-001"],
     "as": "A-002", "want": "paint operations to complete within a frame budget (16ms at 60fps)",
     "so_that": "headless rendering for screenshots and DOM snapshots is fast and predictable",
     "ac": [
         "Frame timing is measured and exposed via an internal performance API",
         "Frames exceeding 16ms are logged with a breakdown of paint phases (layout, raster, composite)",
         "Headless mode skips window presentation but still executes the full paint pipeline",
         "A --no-paint flag skips GPU rendering entirely for DOM-only headless use cases",
     ],
     "standards": ["Performance Timeline (W3C CR)", "Navigation Timing Level 2 (W3C CR)"]},

    # Phase 3 — Interact
    {"id": "US-301", "title": "DOM Event Dispatch (Click, Focus, Keyboard)", "phase": 3, "priority": "P0",
     "personas": ["P-003", "A-001", "A-004"],
     "as": "P-003", "want": "click, focus, blur, and keyboard events to dispatch through the DOM event model (capture → target → bubble)",
     "so_that": "interactive pages respond to my input",
     "ac": [
         "Mouse click events (mousedown, mouseup, click, dblclick) dispatch to the correct target element",
         "Focus and blur events fire on focusable elements with correct activeElement tracking",
         "Keyboard events (keydown, keyup, keypress) dispatch with correct key, code, and modifier properties",
         "Event propagation follows capture → target → bubble phases",
         "event.stopPropagation() and event.preventDefault() work correctly",
     ],
     "standards": ["WHATWG DOM Living Standard (Events)", "UI Events (W3C WD)"]},

    {"id": "US-302", "title": "Form Elements Rendering and Input", "phase": 3, "priority": "P0",
     "personas": ["P-002", "P-003", "A-004"],
     "as": "P-002", "want": "HTML form elements (text input, textarea, select, checkbox, radio, button) to render and accept input",
     "so_that": "I can log into research portals and fill out search forms",
     "ac": [
         "`<input type='text|password|email|search|url|number'>` renders and accepts text input with cursor",
         "`<textarea>` renders with multi-line editing and scrolling",
         "`<select>` renders a dropdown and allows option selection",
         "`<input type='checkbox'>` and `<input type='radio'>` render and toggle state on click",
         "`<button>` and `<input type='submit'>` render and are clickable",
         "Tab key moves focus between form elements in document order (respecting tabindex)",
     ],
     "standards": ["HTML Living Standard §4.10 (Forms)", "WCAG 2.2 SC 2.1.1 (Keyboard)", "WAI-ARIA 1.2"]},

    {"id": "US-303", "title": "Form Submission (GET/POST)", "phase": 3, "priority": "P0",
     "personas": ["A-004", "P-002", "A-001"],
     "as": "A-004", "want": "form submission to send GET or POST requests with encoded form data",
     "so_that": "I can automate login flows and search queries",
     "ac": [
         "Submit button or Enter key in a text field triggers form submission",
         "GET forms append URL-encoded data to the action URL as query parameters",
         "POST forms send URL-encoded data in the request body with correct Content-Type",
         "File inputs are excluded (file upload is out of scope for Phase 3)",
         "Form validation attributes (required, pattern, min/max) prevent submission and show error indicators",
         "Successful submission navigates to the response page",
     ],
     "standards": ["HTML Living Standard §4.10.21 (Form submission)", "RFC 9110 (HTTP methods)"]},

    {"id": "US-304", "title": "JavaScript Engine Integration", "phase": 3, "priority": "P0",
     "personas": ["P-001", "A-001"],
     "as": "P-001", "want": "a JavaScript engine (boa or V8) embedded in the browser that executes `<script>` tags and inline scripts",
     "so_that": "dynamic web pages function",
     "ac": [
         "Inline `<script>` blocks execute in document order during parsing",
         "External `<script src='...'>` files are fetched and executed",
         "`defer` and `async` attributes are respected for execution timing",
         "Script errors are caught and reported to an internal console (not crash the browser)",
         "Each page gets an isolated JS execution context (no cross-page leakage)",
         "Global objects (window, document, navigator, location, console) are available",
     ],
     "standards": ["ECMA-262 (ECMAScript 2025)", "HTML Living Standard §12.2 (Script execution)", "Web IDL (WHATWG)"]},

    {"id": "US-305", "title": "DOM API (Query, Create, Modify)", "phase": 3, "priority": "P0",
     "personas": ["A-001", "P-001", "A-004"],
     "as": "A-001", "want": "the standard DOM API to be available in JavaScript",
     "so_that": "pages that dynamically build their content work correctly",
     "ac": [
         "document.querySelector / querySelectorAll return correct elements for CSS selectors",
         "document.getElementById, getElementsByClassName, getElementsByTagName work",
         "document.createElement creates new elements that can be appended to the DOM",
         "element.appendChild, removeChild, insertBefore, replaceChild modify the tree",
         "element.setAttribute, getAttribute, removeAttribute, classList work",
         "element.textContent and element.innerHTML read and write content",
         "DOM mutations trigger layout recalculation and repaint",
     ],
     "standards": ["WHATWG DOM Living Standard", "WHATWG HTML Living Standard"]},

    {"id": "US-306", "title": "Timers (setTimeout, setInterval)", "phase": 3, "priority": "P1",
     "personas": ["P-001", "A-004"],
     "as": "P-001", "want": "setTimeout and setInterval to schedule callbacks",
     "so_that": "pages with timed behavior (animations, polling, debounce) function correctly",
     "ac": [
         "setTimeout(fn, ms) fires the callback after the specified delay",
         "setInterval(fn, ms) fires the callback repeatedly at the specified interval",
         "clearTimeout and clearInterval cancel pending timers",
         "Timers with delay 0 fire asynchronously (after current script completes)",
         "Timer IDs are unique and do not collide across contexts",
         "Timers are cancelled when the page navigates away",
     ],
     "standards": ["HTML Living Standard §8.6 (Timers)"]},

    {"id": "US-307", "title": "fetch() API", "phase": 3, "priority": "P1",
     "personas": ["A-002", "P-001", "A-004"],
     "as": "A-002", "want": "the JavaScript fetch() API to make HTTP requests and return responses",
     "so_that": "pages that load data dynamically render their full content",
     "ac": [
         "fetch(url) performs a GET request and returns a Promise resolving to a Response",
         "Response.json(), Response.text(), and Response.blob() parse the body",
         "Custom method, headers, and body are supported in the RequestInit options",
         "CORS preflight (OPTIONS) is sent when required; CORS errors are surfaced in console",
         "Network errors reject the promise (not throw synchronously)",
         "AbortController / AbortSignal cancels in-flight requests",
     ],
     "standards": ["WHATWG Fetch Standard", "RFC 9110 (HTTP Semantics)", "CORS (WHATWG Fetch §3)"]},

    {"id": "US-308", "title": "Cookie Management", "phase": 3, "priority": "P1",
     "personas": ["P-005", "A-003", "P-002"],
     "as": "P-005", "want": "the browser to store, send, and manage cookies per RFC 6265",
     "so_that": "I can audit cookie-based authentication and tracking behavior",
     "ac": [
         "Set-Cookie response headers create cookies in the jar",
         "Cookies are sent on subsequent requests matching domain, path, and secure constraints",
         "HttpOnly cookies are not accessible from JavaScript (document.cookie)",
         "Secure cookies are only sent over HTTPS",
         "SameSite (Strict, Lax, None) is enforced",
         "Cookie expiry (Expires, Max-Age) is respected; session cookies clear on browser close",
         "A cookie inspector UI or API lists all cookies with their attributes",
     ],
     "standards": ["RFC 6265bis (Cookies)", "WHATWG HTML Living Standard (document.cookie)"]},

    {"id": "US-309", "title": "Clipboard Integration", "phase": 3, "priority": "P1",
     "personas": ["P-003", "P-002"],
     "as": "P-003", "want": "copy, cut, and paste to work with the system clipboard for text content",
     "so_that": "I can transfer data between the browser and other applications",
     "ac": [
         "Ctrl/Cmd+C copies selected text to the system clipboard",
         "Ctrl/Cmd+X cuts selected text from editable fields",
         "Ctrl/Cmd+V pastes clipboard content into focused editable fields",
         "JavaScript clipboard API (navigator.clipboard.readText/writeText) is available with permission gating",
         "Paste events fire on the target element with clipboardData",
     ],
     "standards": ["Clipboard API (W3C WD)", "Permissions API (W3C CR)"]},

    {"id": "US-310", "title": "Keyboard Navigation and Accessibility", "phase": 3, "priority": "P0",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "full keyboard navigation (Tab, Shift+Tab, Enter, Escape, arrow keys in selects/radios)",
     "so_that": "the browser is usable without a mouse",
     "ac": [
         "Tab and Shift+Tab cycle focus through all interactive elements in DOM order",
         "tabindex attribute overrides natural focus order",
         "Enter activates the focused button or link",
         "Escape closes dropdowns, dialogs, and menus",
         "Arrow keys navigate within select dropdowns and radio button groups",
         "Focus is never trapped in a non-modal container (unless role='dialog' with aria-modal)",
         "Skip-to-content link is supported when present in the page",
     ],
     "standards": ["WCAG 2.2 SC 2.1.1 (Keyboard)", "WCAG 2.2 SC 2.1.2 (No Keyboard Trap)", "WAI-ARIA Authoring Practices Guide"]},

    {"id": "US-311", "title": "Basic Console API", "phase": 3, "priority": "P1",
     "personas": ["P-001", "A-001", "A-003"],
     "as": "P-001", "want": "console.log, console.warn, console.error, and console.info to capture output to an internal log buffer",
     "so_that": "I can debug page scripts",
     "ac": [
         "console.log/warn/error/info capture messages with log level and timestamp",
         "Objects are serialized to a readable format (not [object Object])",
         "console.clear() empties the log buffer",
         "Log entries are accessible via an internal API (for MCP exposure in Phase 4)",
         "Uncaught exceptions and promise rejections are also logged",
     ],
     "standards": ["Console Standard (WHATWG)"]},

    {"id": "US-312", "title": "Content Security and Script Sandboxing", "phase": 3, "priority": "P0",
     "personas": ["P-005", "A-003", "P-001"],
     "as": "P-005", "want": "JavaScript execution to be sandboxed with resource limits",
     "so_that": "malicious scripts cannot crash the browser, access the filesystem, or consume unbounded resources",
     "ac": [
         "Script execution has a configurable CPU time limit per frame (default: 100ms)",
         "Memory usage per script context is bounded (default: 256MB)",
         "Scripts cannot access the filesystem, spawn processes, or open raw sockets",
         "Infinite loops are detected and terminated with a console error",
         "Content-Security-Policy headers are parsed and enforced (script-src at minimum)",
         "A per-site toggle allows disabling JavaScript entirely",
     ],
     "standards": ["CSP Level 3 (W3C WD)", "HTML Living Standard (§7.1 Sandboxing)", "Same-Origin Policy"]},

    # Phase 4 — Connect
    {"id": "US-401", "title": "MCP Server Core and Transport", "phase": 4, "priority": "P0",
     "personas": ["P-001", "A-001", "A-004"],
     "as": "P-001", "want": "the browser to expose an MCP server over stdio and streamable-HTTP transports",
     "so_that": "AI agents can connect and control the browser programmatically",
     "ac": [
         "MCP server starts on browser launch (configurable: --mcp-stdio, --mcp-http=:PORT)",
         "Server implements the MCP protocol (initialize, tool listing, tool invocation, notifications)",
         "Multiple MCP clients can connect simultaneously over HTTP transport",
         "stdio transport supports single-client mode for direct agent piping",
         "Server shuts down cleanly when the browser exits",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-402", "title": "DOM Query Tools", "phase": 4, "priority": "P0",
     "personas": ["A-001", "A-002", "A-004"],
     "as": "A-001", "want": "MCP tools to query the DOM (querySelector, getTextContent, getAttributes, getAccessibilityTree)",
     "so_that": "I can understand page content and answer user questions about what's on screen",
     "ac": [
         "`dom.querySelector(selector)` returns a serialized element (tag, id, classes, attributes, text)",
         "`dom.querySelectorAll(selector)` returns an array of matching elements (paginated for large results)",
         "`dom.getTextContent(selector)` returns visible text content of the matched subtree",
         "`dom.getAttributes(selector)` returns all attributes of the matched element",
         "`dom.getOuterHTML(selector)` returns the HTML markup of the matched subtree",
         "Selectors that match nothing return an empty result (not an error)",
     ],
     "standards": ["WHATWG DOM Living Standard", "CSS Selectors Level 4 (W3C CR)", "MCP Protocol Specification"]},

    {"id": "US-403", "title": "Navigation and Interaction Tools", "phase": 4, "priority": "P0",
     "personas": ["A-004", "A-001", "A-002"],
     "as": "A-004", "want": "MCP tools to navigate pages, click elements, fill form fields, and submit forms",
     "so_that": "I can automate multi-step web workflows end-to-end",
     "ac": [
         "`nav.goto(url)` navigates to a URL and waits for load",
         "`nav.back()` and `nav.forward()` traverse session history",
         "`nav.reload()` reloads the current page",
         "`interact.click(selector)` clicks the first matching element (scrolling into view if needed)",
         "`interact.fill(selector, value)` clears and types into an input/textarea",
         "`interact.select(selector, value)` selects an option in a `<select>` element",
         "`interact.check(selector)` / `interact.uncheck(selector)` toggles checkboxes",
         "`interact.submit(formSelector)` submits a form",
         "All interaction tools wait for resulting navigation or DOM update before returning",
     ],
     "standards": ["MCP Protocol Specification", "HTML Living Standard (Forms)"]},

    {"id": "US-404", "title": "Network Inspection Tools", "phase": 4, "priority": "P1",
     "personas": ["P-005", "A-003", "A-002"],
     "as": "P-005", "want": "MCP tools to inspect network activity (request log, response headers, cookies, active connections)",
     "so_that": "I can audit what data the browser sends and receives",
     "ac": [
         "`network.getRequests(filter?)` returns a list of requests with URL, method, status, headers, timing",
         "`network.getResponse(requestId)` returns full response headers and body (text or base64)",
         "`network.getCookies(domain?)` lists cookies with all attributes",
         "`network.setCookie(cookie)` and `network.deleteCookie(name, domain)` manage the cookie jar",
         "`network.getActiveConnections()` lists open HTTP/WebSocket connections",
         "Request log is circular-buffered (configurable max entries, default 1000)",
     ],
     "standards": ["RFC 9110 (HTTP Semantics)", "RFC 6265bis (Cookies)", "MCP Protocol Specification"]},

    {"id": "US-405", "title": "Layout and Style Inspection Tools", "phase": 4, "priority": "P1",
     "personas": ["A-001", "P-001"],
     "as": "A-001", "want": "MCP tools to inspect element layout (bounding box, computed styles, box model)",
     "so_that": "I can describe visual positioning to users and reason about what's visible on screen",
     "ac": [
         "`layout.getBoundingRect(selector)` returns x, y, width, height relative to viewport",
         "`layout.getComputedStyle(selector, properties?)` returns computed CSS values",
         "`layout.getBoxModel(selector)` returns content, padding, border, and margin dimensions",
         "`layout.isVisible(selector)` reports whether an element is visible",
         "`layout.getScrollPosition()` returns viewport and document scroll offsets",
     ],
     "standards": ["CSSOM View (W3C WD)", "MCP Protocol Specification"]},

    {"id": "US-406", "title": "Accessibility Tree Tools", "phase": 4, "priority": "P1",
     "personas": ["P-004", "A-001", "A-003"],
     "as": "P-004", "want": "MCP tools to expose the browser's accessibility tree",
     "so_that": "agents and testing tools can verify that pages are accessible",
     "ac": [
         "`a11y.getTree(root?)` returns the full or subtree accessibility tree (role, name, state, value per node)",
         "`a11y.getNodeBySelector(selector)` returns the accessibility properties of a specific element",
         "`a11y.findByRole(role)` returns all elements with a given ARIA role",
         "`a11y.findByName(name)` returns elements with a given accessible name",
         "`a11y.checkContrast(selector)` returns foreground/background color and WCAG contrast ratio",
         "Tree output is serializable and diffable for regression testing",
     ],
     "standards": ["WAI-ARIA 1.2 (W3C REC)", "Core-AAM 1.2 (W3C REC)", "ISO/IEC 40500:2025 (WCAG 2.2)", "MCP Protocol Specification"]},

    {"id": "US-407", "title": "Console and Log Tools", "phase": 4, "priority": "P1",
     "personas": ["A-003", "P-005", "P-001"],
     "as": "A-003", "want": "MCP tools to read console output and subscribe to log events in real-time",
     "so_that": "I can monitor for security warnings, CSP violations, and unexpected errors",
     "ac": [
         "`console.getEntries(level?, limit?)` returns buffered console messages",
         "`console.subscribe()` streams new console entries as MCP notifications",
         "`console.clear()` clears the console buffer",
         "CSP violation reports are surfaced as console entries with type 'security'",
         "Mixed-content warnings appear as console entries with type 'security'",
         "Entries include source URL and line number when available",
     ],
     "standards": ["Console Standard (WHATWG)", "CSP Level 3 (violation reporting)", "MCP Protocol Specification"]},

    {"id": "US-408", "title": "Tab Management Tools", "phase": 4, "priority": "P1",
     "personas": ["A-004", "A-001", "A-002"],
     "as": "A-004", "want": "MCP tools to create, list, switch, and close browser tabs",
     "so_that": "I can run multi-page workflows and compare content across tabs",
     "ac": [
         "`tabs.create(url?)` opens a new tab (optionally navigating to a URL)",
         "`tabs.list()` returns all open tabs with id, title, URL, and active status",
         "`tabs.switch(tabId)` makes a tab the active/focused tab",
         "`tabs.close(tabId)` closes a tab",
         "`tabs.getActive()` returns the currently active tab",
         "Tab events (created, closed, navigated, titleChanged) are emitted as MCP notifications",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-409", "title": "Screenshot and Visual Capture Tools", "phase": 4, "priority": "P1",
     "personas": ["A-002", "A-001", "P-001"],
     "as": "A-002", "want": "MCP tools to capture screenshots (full page, viewport, element)",
     "so_that": "I can extract visual content and provide visual context to LLMs",
     "ac": [
         "`capture.screenshot(format?)` captures the current viewport as PNG or JPEG",
         "`capture.fullPage(format?)` captures the entire scrollable page",
         "`capture.element(selector, format?)` captures a specific element's bounding box",
         "Output is returned as base64-encoded data or written to a specified file path",
         "Capture works in both headed and headless modes",
         "Configurable quality for JPEG output (default: 80)",
     ],
     "standards": ["ISO 15948 (PNG)", "ISO/IEC 10918 (JPEG)", "MCP Protocol Specification"]},

    {"id": "US-410", "title": "Agent Permission Model", "phase": 4, "priority": "P0",
     "personas": ["P-005", "A-003"],
     "as": "P-005", "want": "a granular permission model that controls which MCP tools each connected agent can invoke",
     "so_that": "agents operate under least-privilege and cannot perform unauthorized actions",
     "ac": [
         "Agents authenticate with a token or identity on MCP connection",
         "A permission policy maps agent identities to allowed tool namespaces (e.g., read-only, interact, network)",
         "Denied tool invocations return a structured error (not silently fail)",
         "Default policy is read-only (dom.*, layout.*, a11y.*, console.read) — interaction requires explicit grant",
         "Permission changes take effect immediately without server restart",
         "Audit log records all tool invocations with agent identity, tool name, and timestamp",
     ],
     "standards": ["MCP Protocol Specification", "ISO/IEC 27001 (Information Security)", "Principle of Least Privilege"]},

    {"id": "US-411", "title": "Multi-Agent Coordination", "phase": 4, "priority": "P1",
     "personas": ["A-001", "A-003", "A-004"],
     "as": "A-001", "want": "the MCP server to handle multiple connected agents with conflict resolution",
     "so_that": "a copilot agent and a monitoring agent can operate on the same browser without interference",
     "ac": [
         "Multiple agents can connect simultaneously via HTTP transport",
         "Read-only tools (dom.*, layout.*, a11y.*, console.*) execute concurrently without locking",
         "Mutating tools (interact.*, nav.*) acquire an exclusive interaction lock",
         "Lock requests that cannot be immediately fulfilled return a 'busy' status with the holding agent's ID",
         "Agents can subscribe to navigation and DOM-change notifications without invoking tools",
         "Server reports connected agent count and identities via `server.status()` tool",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-412", "title": "MCP Tool Discovery and Documentation", "phase": 4, "priority": "P2",
     "personas": ["P-001", "A-001"],
     "as": "P-001", "want": "the MCP server to provide rich tool metadata (descriptions, parameter schemas, examples)",
     "so_that": "agents and developers can discover and use tools without external documentation",
     "ac": [
         "Every tool has a human-readable description and parameter JSON Schema",
         "Tool listing includes categorization by namespace (dom, nav, interact, network, layout, a11y, console, tabs, capture)",
         "Parameter schemas use descriptive field names and include default values",
         "Error responses include structured error codes and human-readable messages",
         "A `server.version()` tool returns the browser version and supported MCP protocol version",
     ],
     "standards": ["MCP Protocol Specification", "JSON Schema (IETF)"]},

    # Phase 5 — Extend
    {"id": "US-501", "title": "Plugin Manifest Format and Loading", "phase": 5, "priority": "P0",
     "personas": ["P-001", "A-001"],
     "as": "P-001", "want": "a declarative plugin manifest format (TOML/JSON) that declares permissions, entry points, and metadata",
     "so_that": "I can package and distribute browser plugins with a predictable structure",
     "ac": [
         "Manifest schema is documented with required fields: name, version, permissions, entry points, author, description",
         "Browser discovers and loads plugins from a designated plugins directory on startup",
         "Invalid or malformed manifests produce clear error messages and do not crash the browser",
         "Plugin loading is lazy — code is not executed until the plugin is activated",
         "Manifest supports declaring minimum browser version compatibility",
     ],
     "standards": ["Chrome Extensions Manifest V3 (reference architecture)"]},

    {"id": "US-502", "title": "Content Script Injection", "phase": 5, "priority": "P0",
     "personas": ["P-001", "A-001", "A-002"],
     "as": "P-001", "want": "to inject JavaScript and CSS into specific web pages based on URL match patterns",
     "so_that": "I can modify page behavior and appearance on a per-site basis",
     "ac": [
         "Content scripts are declared in the plugin manifest with URL match patterns (glob and regex)",
         "CSS is injected before first paint; JS is injected at configurable run timing (document_start, document_end, document_idle)",
         "Injected scripts run in an isolated world — they share DOM access but not JS global scope with the page",
         "Content scripts can communicate with the plugin background script via a message-passing API",
         "URL match patterns support include and exclude lists",
     ],
     "standards": ["Same-Origin Policy (isolated worlds)", "CSP Level 3 (script injection implications)"]},

    {"id": "US-503", "title": "Plugin API — DOM, Network, and Storage Access", "phase": 5, "priority": "P0",
     "personas": ["P-001", "A-001", "A-004"],
     "as": "P-001", "want": "a well-defined plugin API that provides controlled access to DOM inspection, network request interception, and persistent key-value storage",
     "so_that": "I can build powerful extensions without relying on fragile hacks",
     "ac": [
         "DOM API allows reading and mutating page DOM from content scripts",
         "Network API allows observing, modifying, and blocking HTTP requests/responses (declarativeNetRequest-style)",
         "Storage API provides persistent key-value storage scoped per plugin (sync and local tiers)",
         "All API surfaces require explicit permission grants declared in the manifest",
         "API calls from unpermitted plugins return clear permission-denied errors",
         "API is versioned with a stability contract (stable, experimental, deprecated)",
     ],
     "standards": ["Chrome Extensions API (reference)", "Permissions Policy"]},

    {"id": "US-504", "title": "Plugin Sandboxing via WASM Isolation", "phase": 5, "priority": "P0",
     "personas": ["P-005", "A-003", "P-001"],
     "as": "P-005", "want": "plugins to execute inside WASM sandboxes with capability-based permissions",
     "so_that": "a malicious or buggy plugin cannot compromise the browser process or access unauthorized data",
     "ac": [
         "Plugin background scripts run inside a WASM sandbox (e.g., Wasmtime) with no direct host access",
         "Sandbox enforces capability-based permissions — only manifest-declared APIs are available",
         "Memory and CPU limits are configurable per plugin; exceeding limits terminates the plugin gracefully",
         "File system access is virtualized and scoped to the plugin's storage directory",
         "Sandbox escape attempts are logged and reported to the user",
         "Plugin crashes are isolated — they do not affect other plugins or the browser process",
     ],
     "standards": ["WebAssembly Core Spec (W3C REC)", "ISO/IEC 15408 (Common Criteria — FDP data protection)"]},

    {"id": "US-505", "title": "Plugin Marketplace and Registry", "phase": 5, "priority": "P1",
     "personas": ["P-001", "P-005", "P-003"],
     "as": "P-001", "want": "a plugin registry where I can publish, discover, and install plugins",
     "so_that": "the ecosystem can grow and users can find useful extensions",
     "ac": [
         "CLI tool or browser UI can search, install, update, and uninstall plugins from the registry",
         "Registry hosts plugin manifests, signatures, and download URLs (not necessarily binaries)",
         "Plugins are signed with author keys; unsigned plugins require explicit user consent",
         "Registry supports versioning with semver and dependency declarations",
         "Users can rate and flag plugins; flagged plugins are reviewed before removal",
         "Self-hosted registry option for enterprise/private deployments",
     ],
     "standards": ["SLSA Framework (supply chain integrity)", "Sigstore (code signing)"]},

    {"id": "US-506", "title": "Theming Engine for Browser Chrome", "phase": 5, "priority": "P1",
     "personas": ["P-003", "P-004", "P-001"],
     "as": "P-003", "want": "to customize the browser chrome (toolbar, tabs, sidebar, status bar) with custom CSS themes",
     "so_that": "I can make the browser match my aesthetic and reduce visual fatigue",
     "ac": [
         "Themes are packaged as plugin-type manifests with CSS targeting browser chrome components",
         "Theme CSS uses a defined set of custom properties (--trb-bg-primary, --trb-text-primary, etc.) for stable theming",
         "Theme switching is instant (no restart required) and previews are available before applying",
         "Built-in light, dark, and high-contrast themes ship with the browser",
         "Themes cannot inject scripts or access page content — CSS only",
         "Invalid theme CSS is gracefully ignored without breaking chrome layout",
     ],
     "standards": ["CSS Custom Properties (W3C CR)", "WCAG 2.2 SC 1.4.3 (Contrast for high-contrast themes)"]},

    {"id": "US-507", "title": "Plugin-to-Plugin Communication", "phase": 5, "priority": "P2",
     "personas": ["P-001", "A-001", "A-004"],
     "as": "P-001", "want": "plugins to send messages to other installed plugins via a typed message bus",
     "so_that": "I can build composable extensions that interoperate without tight coupling",
     "ac": [
         "Plugins can declare public message channels in their manifest",
         "Sending plugin specifies target plugin ID and channel; receiving plugin registers handlers",
         "Messages are serialized (JSON) and validated against optional schema declarations",
         "Communication requires mutual opt-in — receiver must declare willingness to accept messages from external plugins",
         "Message delivery is async with optional response callbacks",
         "Rate limiting prevents message flooding between plugins",
     ],
     "standards": ["JSON Schema (IETF)"]},

    {"id": "US-508", "title": "Agent-as-Plugin Installation", "phase": 5, "priority": "P1",
     "personas": ["A-001", "A-003", "A-004", "P-001"],
     "as": "A-001", "want": "to be installable as a browser plugin with access to the plugin API",
     "so_that": "I can integrate deeply with the browsing experience using the same extension model as human-authored plugins",
     "ac": [
         "Agent plugins use the same manifest format as standard plugins with an additional `agent` section declaring LLM provider, model, and tool permissions",
         "Agent plugins have access to the full plugin API surface (DOM, network, storage) subject to manifest permissions",
         "Agent plugins can register for browser events (navigation, tab create/close, page load) as triggers",
         "Users can enable/disable agent plugins and review their permission grants independently",
         "Agent plugins can invoke other plugins via the plugin-to-plugin message bus",
         "Agent resource usage (API calls, tokens, compute) is tracked and surfaced in a dashboard",
     ],
     "standards": ["MCP Protocol Specification"]},

    {"id": "US-509", "title": "Plugin DevTools and Debugging", "phase": 5, "priority": "P1",
     "personas": ["P-001"],
     "as": "P-001", "want": "a built-in plugin developer console that shows logs, API calls, permission checks, and sandbox state",
     "so_that": "I can debug plugins efficiently during development",
     "ac": [
         "Plugin DevTools panel is accessible from the browser's developer tools",
         "Console shows plugin logs, API call traces, and permission grant/deny events",
         "Live reload is supported — saving a manifest or script triggers hot reload without browser restart",
         "Breakpoints can be set in content scripts and background scripts",
         "Sandbox memory and CPU usage are visible in real time",
         "Error messages include actionable suggestions (e.g., 'Permission network.intercept not declared in manifest')",
     ],
     "standards": []},

    {"id": "US-510", "title": "Plugin Permission Escalation Controls", "phase": 5, "priority": "P0",
     "personas": ["P-005", "A-003", "P-003"],
     "as": "P-005", "want": "plugin permission changes on update to require explicit user re-approval",
     "so_that": "a trusted plugin cannot silently escalate its access after installation",
     "ac": [
         "Plugin updates that add new permissions trigger a user approval prompt before activation",
         "The prompt clearly shows which permissions are new vs. previously granted",
         "Users can reject the new permissions and remain on the previous version",
         "Permission downgrades (removing permissions) are applied silently",
         "A full permission audit log is available per plugin showing all grants and changes over time",
     ],
     "standards": ["ISO/IEC 27001 (access control)", "Principle of Least Privilege"]},

    # Phase 6 — Comply
    {"id": "US-601", "title": "ACID2 Test Pass", "phase": 6, "priority": "P0",
     "personas": ["P-001", "A-002"],
     "as": "P-001", "want": "the browser's rendering engine to pass the ACID2 test completely",
     "so_that": "I can trust that fundamental CSS box model, positioning, and rendering are correct",
     "ac": [
         "Browser renders the ACID2 reference page pixel-perfectly matching the reference rendering",
         "No visual artifacts, misaligned elements, or incorrect stacking",
         "ACID2 pass is verified in CI via headless screenshot comparison with tolerance < 1%",
         "Regressions against ACID2 block merges to main",
     ],
     "standards": ["CSS 2.1 (W3C REC)", "Acid2 Test Suite", "PNG Spec (RFC 2083 — alpha transparency)"]},

    {"id": "US-602", "title": "ACID3 Test Target (>95/100)", "phase": 6, "priority": "P1",
     "personas": ["P-001", "A-002"],
     "as": "P-001", "want": "the browser to score at least 95/100 on the ACID3 test",
     "so_that": "I can verify broad compliance with DOM, CSS, and ECMAScript standards",
     "ac": [
         "Browser scores >= 95/100 on the ACID3 test suite",
         "Failing subtests are documented with root cause and priority for future fixes",
         "ACID3 score is tracked in CI with a regression threshold (score cannot decrease)",
         "Known intentional deviations (if any) are documented with rationale",
     ],
     "standards": ["DOM Level 2 (Traversal, Range, Core, Events, Style)", "CSS Selectors Level 3", "SVG 1.1", "ECMA-262", "Acid3 Test Suite (deprecated but useful as integration test)"]},

    {"id": "US-603", "title": "Full Accessibility Tree", "phase": 6, "priority": "P0",
     "personas": ["P-004", "A-001", "P-003"],
     "as": "P-004", "want": "the browser to build a complete accessibility tree from the DOM with correct ARIA roles, states, and properties",
     "so_that": "assistive technologies receive accurate semantic information about page content",
     "ac": [
         "Every DOM element maps to an appropriate accessibility tree node with computed role, name, and description",
         "ARIA attributes (role, aria-label, aria-labelledby, aria-describedby, aria-expanded, aria-checked, etc.) are reflected in the tree",
         "Implicit roles from HTML semantics (button, nav, main, article, etc.) are correctly computed",
         "Accessibility tree updates in response to DOM mutations (dynamic content, AJAX)",
         "Tree is inspectable via browser DevTools accessibility panel",
         "Accessibility tree conforms to the WAI-ARIA 1.2 specification",
     ],
     "standards": ["WAI-ARIA 1.2 (W3C REC)", "HTML-AAM 1.0 (W3C CR)", "Core-AAM 1.2 (W3C REC)", "ISO/IEC 40500:2025 (WCAG 2.2)", "EN 301 549 v3.2.1 Ch.11"]},

    {"id": "US-604", "title": "Screen Reader Integration", "phase": 6, "priority": "P0",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "the browser to integrate with platform accessibility APIs (macOS Accessibility, AT-SPI on Linux, UIA on Windows)",
     "so_that": "screen readers like VoiceOver, Orca, and NVDA can read and navigate web content",
     "ac": [
         "Browser exposes the accessibility tree via the platform's native accessibility API",
         "Screen readers can read page content, navigate by headings/landmarks/links, and interact with form controls",
         "Live regions (aria-live) trigger screen reader announcements on content change",
         "Focus changes are communicated to the screen reader in real time",
         "Integration is tested with at least one screen reader per platform (VoiceOver, Orca, NVDA)",
         "Browser chrome (toolbar, tabs, menus) is also accessible via screen reader",
     ],
     "standards": ["macOS NSAccessibility Protocol", "Linux AT-SPI2 (D-Bus)", "Windows UIA (UI Automation)", "ISO/IEC 40500:2025 (WCAG 2.2)", "EN 301 549 v3.2.1 Ch.11", "Section 508 (US)"]},

    {"id": "US-605", "title": "Keyboard Navigation and Focus Management (Compliance)", "phase": 6, "priority": "P0",
     "personas": ["P-003", "P-004", "A-001"],
     "as": "P-003", "want": "complete keyboard navigation with correct tab order, focus indicators, and skip links",
     "so_that": "I can use the browser and web content entirely without a mouse",
     "ac": [
         "Tab key cycles through all focusable elements in document order (or tabindex order)",
         "Focus indicators are always visible and meet WCAG 2.2 contrast requirements",
         "Skip-to-content mechanism is available for pages with navigation",
         "Arrow keys navigate within composite widgets (menus, tabs, trees, grids) per WAI-ARIA authoring practices",
         "Focus trapping works correctly in modal dialogs",
         "Browser chrome is fully keyboard-navigable (address bar, tabs, menus, settings)",
         "Custom focus order via tabindex is respected",
     ],
     "standards": ["WCAG 2.2 SC 2.1.1 (Keyboard)", "WCAG 2.2 SC 2.4.7 (Focus Visible)", "WCAG 2.2 SC 2.4.11 (Focus Appearance)", "WAI-ARIA Authoring Practices Guide"]},

    {"id": "US-606", "title": "CSS Flexbox Layout", "phase": 6, "priority": "P0",
     "personas": ["P-001", "A-002"],
     "as": "P-001", "want": "the rendering engine to fully support CSS Flexbox layout",
     "so_that": "modern web pages using flex containers render correctly",
     "ac": [
         "All Flexbox properties are supported: display:flex, flex-direction, flex-wrap, justify-content, align-items, align-content, flex-grow, flex-shrink, flex-basis, order, align-self, gap",
         "Passes the CSS Flexbox test suite from web-platform-tests (>95% pass rate)",
         "Nested flex containers render correctly",
         "Flex layout interacts correctly with min/max constraints, overflow, and margins",
     ],
     "standards": ["CSS Flexbox Level 1 (W3C CR)", "Web Platform Tests (css/css-flexbox/)"]},

    {"id": "US-607", "title": "CSS Grid Layout", "phase": 6, "priority": "P0",
     "personas": ["P-001", "A-002"],
     "as": "P-001", "want": "the rendering engine to fully support CSS Grid layout",
     "so_that": "complex two-dimensional page layouts render correctly",
     "ac": [
         "All Grid properties are supported: display:grid, grid-template-columns/rows, grid-template-areas, grid-column/row, grid-gap, auto-fill/auto-fit, minmax(), repeat()",
         "Passes the CSS Grid test suite from web-platform-tests (>90% pass rate)",
         "Implicit and explicit grid tracks are computed correctly",
         "Grid layout interacts correctly with Flexbox, positioning, and overflow",
     ],
     "standards": ["CSS Grid Level 1 (W3C CR)", "CSS Grid Level 2 (W3C CR)", "Web Platform Tests (css/css-grid/)"]},

    {"id": "US-608", "title": "Media Queries and Responsive Layout", "phase": 6, "priority": "P1",
     "personas": ["A-002", "P-001"],
     "as": "A-002", "want": "the browser to support CSS media queries for viewport dimensions, resolution, and prefers-color-scheme",
     "so_that": "I can render pages as they appear across different device configurations",
     "ac": [
         "Media queries for width, height, min-width, max-width, min-height, max-height are evaluated correctly",
         "Device-pixel-ratio and resolution queries are supported",
         "prefers-color-scheme and prefers-reduced-motion queries reflect browser/OS settings",
         "Viewport resizing triggers media query re-evaluation and layout reflow",
         "Headless mode supports configurable viewport dimensions for responsive testing",
     ],
     "standards": ["CSS Media Queries Level 4 (W3C CR)", "CSS Media Queries Level 5 (W3C WD)"]},

    {"id": "US-609", "title": "Web Fonts (@font-face)", "phase": 6, "priority": "P1",
     "personas": ["P-002", "P-001", "A-002"],
     "as": "P-002", "want": "the browser to support @font-face declarations for loading custom web fonts",
     "so_that": "pages render with their intended typography",
     "ac": [
         "@font-face rules are parsed and fonts are fetched from declared URLs",
         "WOFF, WOFF2, TTF, and OTF formats are supported",
         "Font loading does not block initial render — fallback fonts display until custom fonts load (FOUT behavior configurable)",
         "Font subsetting via unicode-range is respected",
         "Font loading failures fall back gracefully to the next font in the stack",
         "Font cache persists across sessions to avoid redundant downloads",
     ],
     "standards": ["CSS Fonts Level 4 (W3C CR)", "WOFF 2.0 (W3C REC)", "OpenType spec (ISO/IEC 14496-22)"]},

    {"id": "US-610", "title": "CSS Animations and Transitions", "phase": 6, "priority": "P1",
     "personas": ["P-003", "P-001", "A-002"],
     "as": "P-003", "want": "the browser to support CSS transitions and keyframe animations",
     "so_that": "interactive UI elements respond smoothly and pages with motion design render correctly",
     "ac": [
         "CSS transition properties (transition-property, transition-duration, transition-timing-function, transition-delay) are supported",
         "CSS @keyframes animations with animation-* properties are supported",
         "Hardware-accelerated properties (transform, opacity) are composited on the GPU when available",
         "prefers-reduced-motion media query disables or reduces animations when set",
         "Animation frame rate targets 60fps; dropped frames are recoverable without layout thrash",
         "JavaScript animation APIs (requestAnimationFrame, Web Animations API) are supported",
     ],
     "standards": ["CSS Transitions Level 1 (W3C CR)", "CSS Animations Level 1 (W3C CR)", "Web Animations (W3C CR)", "WCAG 2.2 SC 2.3.3 (Animation from Interactions)"]},

    {"id": "US-611", "title": "High-Contrast and Forced-Colors Mode (Compliance)", "phase": 6, "priority": "P1",
     "personas": ["P-004", "P-003"],
     "as": "P-004", "want": "the browser to support forced-colors mode and the prefers-contrast media query",
     "so_that": "users with low vision can override page colors for readability",
     "ac": [
         "forced-colors: active mode overrides page colors with system-defined high-contrast palette",
         "prefers-contrast media query (no-preference, more, less, custom) is supported",
         "System color keywords (Canvas, CanvasText, LinkText, etc.) resolve correctly in forced-colors mode",
         "Authors can use forced-color-adjust to opt specific elements out of forced colors",
         "High-contrast mode is togglable from browser settings without OS-level changes",
     ],
     "standards": ["CSS Color Adjust Level 1", "WCAG 2.2 SC 1.4.11 (Non-text Contrast)", "EN 301 549 §11.7"]},

    # Phase 7 — Ship
    {"id": "US-701", "title": "Cross-Platform Packaging", "phase": 7, "priority": "P0",
     "personas": ["P-001", "P-003"],
     "as": "P-001", "want": "the browser to produce native packages for macOS (.dmg/.app), Linux (.deb, .rpm, AppImage), and Windows (.msi, .exe)",
     "so_that": "users can install it through familiar platform mechanisms",
     "ac": [
         "CI pipeline produces signed release artifacts for all three platforms",
         "macOS build is a universal binary (arm64 + x86_64) in a signed and notarized .dmg",
         "Linux builds include .deb (Debian/Ubuntu), .rpm (Fedora/RHEL), and AppImage",
         "Windows build is a signed .msi installer with optional .exe portable variant",
         "Each package registers file associations (HTML, XHTML) and as a default browser candidate",
         "Package size is documented and tracked; bloat regressions trigger CI warnings",
     ],
     "standards": ["Apple Notarization Requirements", "Windows Authenticode Signing", "RPM Signing Guidelines"]},

    {"id": "US-702", "title": "Auto-Update Mechanism", "phase": 7, "priority": "P0",
     "personas": ["P-003", "P-005", "P-001"],
     "as": "P-003", "want": "the browser to check for and install updates automatically in the background",
     "so_that": "I always have the latest features and security fixes without manual intervention",
     "ac": [
         "Browser checks for updates on a configurable schedule (default: daily)",
         "Updates download in the background without interrupting browsing",
         "User is notified when an update is ready and can defer or apply immediately",
         "Updates are verified via cryptographic signatures before installation",
         "Rollback to the previous version is available if the update causes issues",
         "Update channel selection is supported (stable, beta, nightly)",
         "Auto-update can be disabled entirely for managed/enterprise deployments",
     ],
     "standards": ["SLSA Framework (update integrity)", "TUF (The Update Framework)"]},

    {"id": "US-703", "title": "Opt-In Crash Reporting and Telemetry", "phase": 7, "priority": "P0",
     "personas": ["P-001", "P-005", "A-003"],
     "as": "P-001", "want": "an opt-in crash reporting and anonymous usage telemetry system",
     "so_that": "I can identify and fix stability issues in the wild",
     "ac": [
         "Crash reporter captures minidump, stack trace, browser version, OS version, and loaded plugins",
         "Telemetry is strictly opt-in — disabled by default with clear first-run prompt",
         "Users can review exactly what data will be sent before opting in",
         "Telemetry data is anonymized — no PII, no browsing history, no page content",
         "Crash reports are uploaded to a self-hosted endpoint (not a third-party service)",
         "Opt-in status can be changed at any time from settings",
         "A local crash log is always available regardless of opt-in status",
     ],
     "standards": ["GDPR (data minimization, consent)", "ISO/IEC 27001 (information security)"]},

    {"id": "US-704", "title": "User Profile and Sync", "phase": 7, "priority": "P1",
     "personas": ["P-002", "P-003", "P-005"],
     "as": "P-002", "want": "to create a user profile that stores my settings, bookmarks, history, and plugin configuration, and optionally sync it across devices",
     "so_that": "my browsing environment is consistent everywhere I work",
     "ac": [
         "User profile stores: settings, bookmarks, history, cookies, plugin list, theme, and saved passwords",
         "Multiple profiles are supported with fast profile switching",
         "Optional sync via encrypted cloud storage (user-provided endpoint or built-in service)",
         "Sync uses end-to-end encryption — the server cannot read profile data",
         "Conflict resolution for concurrent edits (last-write-wins with merge for bookmarks)",
         "Profiles can be exported and imported as encrypted archives",
     ],
     "standards": ["NIST SP 800-63B (credential storage)", "ISO/IEC 27001 (data protection)"]},

    {"id": "US-705", "title": "Bookmark Management", "phase": 7, "priority": "P1",
     "personas": ["P-002", "P-003", "A-001"],
     "as": "P-002", "want": "a bookmark manager with folders, tags, search, and import/export",
     "so_that": "I can organize and retrieve my research references efficiently",
     "ac": [
         "Bookmarks support folders (nested), tags, and descriptions",
         "Full-text search across bookmark titles, URLs, tags, and descriptions",
         "Import from Chrome, Firefox, and Safari bookmark formats (HTML and JSON)",
         "Export to HTML and JSON formats",
         "Bookmarks bar is toggleable and supports drag-and-drop reordering",
         "Duplicate bookmark detection warns before creating duplicates",
         "Keyboard shortcut to bookmark current page (Ctrl/Cmd+D)",
     ],
     "standards": ["Netscape Bookmark File Format (HTML export compatibility)"]},

    {"id": "US-706", "title": "Password Manager Integration", "phase": 7, "priority": "P1",
     "personas": ["P-005", "P-003", "P-002"],
     "as": "P-005", "want": "the browser to integrate with system keychain and third-party password managers (1Password, Bitwarden) via their browser extension APIs",
     "so_that": "users can autofill credentials securely without a built-in password store",
     "ac": [
         "Browser exposes the Web Credentials API for password manager extensions to hook into",
         "Native messaging host protocol is supported for communicating with external password managers",
         "Built-in minimal credential store uses OS keychain (macOS Keychain, GNOME Keyring, Windows Credential Manager)",
         "Autofill UI shows credential suggestions on login forms without exposing passwords in plaintext",
         "Users can disable built-in credential storage entirely if using an external manager",
         "Credential autofill works with both standard and shadow-DOM login forms",
     ],
     "standards": ["Credential Management API (W3C CR)", "NIST SP 800-63B", "Web Authentication API (WebAuthn, W3C REC)"]},

    {"id": "US-707", "title": "Download Manager", "phase": 7, "priority": "P1",
     "personas": ["P-003", "P-002", "A-002"],
     "as": "P-003", "want": "a download manager that shows progress, supports pause/resume, and lets me organize downloads by type",
     "so_that": "I can manage file downloads efficiently",
     "ac": [
         "Download progress bar shows speed, percentage, and estimated time remaining",
         "Downloads can be paused and resumed (if server supports Range requests)",
         "Default download directory is configurable; 'ask every time' option is available",
         "Download history is searchable and clearable",
         "Dangerous file type warnings (executables, scripts) require explicit user confirmation",
         "Completed downloads can be opened or revealed in the file manager from the UI",
         "Keyboard shortcut opens the download manager (Ctrl/Cmd+J)",
     ],
     "standards": ["RFC 9110 §14.2 (Range Requests)", "Safe Browsing (download hash check)"]},

    {"id": "US-708", "title": "Print Support", "phase": 7, "priority": "P2",
     "personas": ["P-002", "P-001"],
     "as": "P-002", "want": "to print web pages and save them as PDF with correct pagination, headers/footers, and print-specific stylesheets",
     "so_that": "I can produce physical or archival copies of research material",
     "ac": [
         "Print dialog supports page range, copies, orientation, and paper size selection",
         "Save-to-PDF produces a high-quality PDF with selectable text and embedded fonts",
         "@media print stylesheets are applied during print rendering",
         "Page breaks (break-before, break-after, break-inside) are respected",
         "Headers and footers (page number, URL, date) are configurable",
         "Print preview is available before committing to print",
         "Background graphics printing is optional (off by default)",
     ],
     "standards": ["ISO 32000-2:2020 (PDF 2.0)", "CSS Paged Media Level 3 (W3C WD)", "CSS Fragmentation Level 3 (W3C CR)"]},

    {"id": "US-709", "title": "First-Run Experience and Onboarding", "phase": 7, "priority": "P1",
     "personas": ["P-003", "P-004", "P-002"],
     "as": "P-003", "want": "a concise first-run onboarding flow that lets me import data from other browsers, set defaults, and learn key features",
     "so_that": "I can be productive immediately without reading documentation",
     "ac": [
         "First-run wizard launches on initial startup with 3-5 steps maximum",
         "Import step offers to import bookmarks, history, passwords, and settings from Chrome, Firefox, and Safari",
         "Default browser prompt is shown (with option to skip)",
         "Quick tour highlights key differentiating features (agent integration, keyboard shortcuts, privacy controls)",
         "Theme selection (light/dark/system) is offered during onboarding",
         "Telemetry opt-in is presented with clear explanation",
         "Onboarding can be skipped entirely with a single click",
         "Onboarding can be re-accessed from settings",
     ],
     "standards": ["WCAG 2.2 (onboarding UI must be accessible)", "EN 301 549 §11 (software accessibility)"]},

    {"id": "US-710", "title": "Agent Onboarding and Defaults", "phase": 7, "priority": "P1",
     "personas": ["A-001", "A-004", "P-001", "P-003"],
     "as": "A-001", "want": "the first-run experience to include an agent setup step where users can enable/disable bundled agents and configure their API keys",
     "so_that": "the AI-native features are discoverable and correctly configured from the start",
     "ac": [
         "Onboarding includes an optional 'AI Assistant' step after basic setup",
         "Bundled agents are listed with descriptions, permission summaries, and enable/disable toggles",
         "API key configuration (for LLM providers) is handled in this step with validation",
         "Users who skip agent setup can configure agents later from settings",
         "Default agent permissions are conservative — users must explicitly grant elevated access",
         "A brief demo or example interaction shows what agents can do",
     ],
     "standards": ["MCP Protocol Specification", "Principle of Least Privilege"]},

    {"id": "US-711", "title": "Release Signing and Supply Chain Security", "phase": 7, "priority": "P0",
     "personas": ["P-005", "A-003", "P-001"],
     "as": "P-005", "want": "all release artifacts to be reproducibly built, cryptographically signed, and published with SLSA provenance attestations",
     "so_that": "users can verify the integrity and provenance of every download",
     "ac": [
         "CI builds are reproducible — same source commit produces bit-identical artifacts",
         "All binaries are signed with the project's code-signing certificate (per-platform)",
         "SLSA Level 3 provenance attestations are generated and published alongside releases",
         "SHA-256 checksums are published for every artifact",
         "Users can verify signatures via a documented process in the release notes",
         "Build pipeline is hardened against dependency confusion and typosquatting attacks",
     ],
     "standards": ["SLSA Framework v1.1", "Sigstore (cosign)", "EU Cyber Resilience Act", "US EO 14028 (software supply chain)"]},
]


def persona_table(persona_ids):
    rows = []
    for pid in persona_ids:
        name, role = PERSONAS[pid]
        rows.append(f"| {pid} | {name} | {role} |")
    return "\n".join(rows)


def write_story(s):
    phase_name, milestone = PHASES[s["phase"]]
    primary_persona = PERSONAS[s["as"]]
    standards_yaml = ", ".join(f'"{st}"' for st in s.get("standards", []))

    content = f"""---
id: {s["id"]}
title: "{s["title"]}"
phase: {s["phase"]}
phase_name: {phase_name}
priority: {s["priority"]}
personas: [{", ".join(s["personas"])}]
standards: [{standards_yaml}]
---

# {s["id"]}: {s["title"]}

**As** {s["as"]} {primary_persona[0]} ({primary_persona[1]}), **I want** {s["want"]}, **so that** {s["so_that"]}.

## Acceptance Criteria

"""
    for ac in s["ac"]:
        content += f"- [ ] {ac}\n"

    content += f"""
## Personas

| ID | Name | Role |
|---|---|---|
{persona_table(s["personas"])}

## Phase Context

**Phase:** {s["phase"]} — {phase_name}
**Milestone:** {milestone}
"""
    filepath = os.path.join(STORIES_DIR, f"{s['id']}.md")
    with open(filepath, "w") as f:
        f.write(content)


for story in stories:
    write_story(story)

print(f"Generated {len(stories)} story files in {STORIES_DIR}")
