locals {
  account_id = "a75e745949fc104ea4c4107a17158f15"
  server_ip  = "208.64.36.79"

  domains = toset([
    "aifighter.com",
    "ailurophileanonymous.com",
    "app-guru.com",
    "bladeofeternity.com",
    "bloggerscompete.com",
    "bookmarkflow.com",
    "codefre.sh",
    "elixirgenai.dev",
    "exllama.dev",
    "fantasticwingedavenger.com",
    "gameclick.net",
    "gamesborn.com",
    "genleo.net",
    "gotta.cc",
    "hirewritingexperts.com",
    "inmateslife.com",
    "iotgo.io",
    "jailbreakingsite.com",
    "justmcp.it.com",
    "justsecure.it.com",
    "kingofthepeople.com",
    "leadingbanner.com",
    "malicious-gamers.com",
    "malicious-mercenaries.com",
    "malicious-mobbers.com",
    "mangioneforsenate.com",
    "mangioneinthewhitehouse.com",
    "mcpjumpst.art",
    "noizu.ink",
    "noizulabs.com",
    "noizurpg.com",
    "onlineemploymentopportunities.org",
    "phpconform.com",
    "phpspec.org",
    "preejaculationx.com",
    "robots-unite.com",
    "secureasfrak.com",
    "smah.pro",
    "symptoms-of-lymphoma.net",
    "textrpg.org",
    "thefutureismangione.com",
    "therobotlearns.blog",
    "therobotlearns.com",
    "therobotlearns.to",
    "thismcp.codes",
    "youngcelebrities.net",
  ])
}
