---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-basic-auth
  namespace: infra
spec:
  encryptedData:
    auth: AgASIwYNX+c9Bv3ZZMOWJ1LquUqM8oV73kV+XxEuZE0UsjDFbyoCziMEOS7gV4W8pTppitUUQGNOpnrsqKoCC5YLYG0RawU5ggVBhnwLqF4JBnLT6JVABjeEp/tjzcrstkS2FndsXEdkjB8Q7T6lhCoHCQBDwNFSnhc4jYUBbT/7eI2Z14DuWbo4rtpU5BlUk8V6i8dxoFDN+6WkZc8QuGXGbcOgAF0+lS64Tr6gKNSwR50fnEO4jMlAz1HfgVVVLsd3ZYoFayemwDfaNM5mlJK655v6TfZUc4ck7fucn75bp7qZfWbRzv9W1GYnO5KaSMDFnjlMVYZBF/ohnLDhcc9yb4pJEnF6InWzliaVIUaCIToaksBISp44yH0dJQ+4+k2CpTprkv9t4FDsJn+8gdNRmIh6o31BrYxNVesOKK33OysoAzk2jGS06VCz3gfwB0rwrlLnuLVU7EJvF7mra+AyNSQf1bYeAROrYvRNo+Q5EUW4rNJ3W6JuE40ebUaeWwi3reKXtt6hHtwMg/Dqhm0rhiy+YOtUX0UgmThEVwx2Z2wy8vtJg79yNE/B1D8OKZZeBRWWVPtPUWJ/w9ox40HFM0XG/54pAb/85MfgH3CyuajvNnh3J2E4KcVBbHVYbzWrUiX5cCEATATjj3Xulu8LbbuNKRazo9nZeF325gSRtX1c1/rIn+qeuWyMROVaaTUoawucBi49W7MUHR41bwKJUdLnGvj6R+mWLrnK7pC3dOsU8pA3kRk9GQvotVA+ggMkoJgh7ATU2xEtq8+R+vE3
  template:
    metadata:
      name: registry-basic-auth
      namespace: infra
