#!/usr/bin/env bash
# Seal the ops.noizu.com TLS cert into secrets/ops-noizu-com-tls.sealedsecret.yaml
# (committed, encrypted, consumed by secrets.tf). This is the ONLY secret still
# sealed for the infra module — everything else is generated by init and
# rendered natively (see managed-secrets.tf).
#
# The cert+key live in the central, gitignored secrets store:
#   <repo>/.secrets/tls/ops.noizu.com/{cert.pem,key.pem}
# Recover them from a cluster backup with ./recover-ops-tls.sh if missing.
#
# Requires: kubectl + kubeseal, with the sealed-secrets controller running
# (installed by init into kube-system as sealed-secrets-controller).
#
#   ./seal-secrets.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$HERE" rev-parse --show-toplevel)"

TARGET_NS="${TARGET_NS:-infra}"
CONTROLLER_NS="${CONTROLLER_NS:-kube-system}"
CONTROLLER_NAME="${CONTROLLER_NAME:-sealed-secrets-controller}"

TLS_DIR="${OPS_TLS_DIR:-$REPO_ROOT/.secrets/tls/ops.noizu.com}"
CRT="$TLS_DIR/cert.pem"
KEY="$TLS_DIR/key.pem"
OUT="$HERE/secrets/ops-noizu-com-tls.sealedsecret.yaml"

if [[ ! -f "$CRT" || ! -f "$KEY" ]]; then
  echo "Missing $CRT and/or $KEY." >&2
  echo "Recover them from the cluster backup first:  ./recover-ops-tls.sh" >&2
  exit 1
fi

echo ">> sealing ops-noizu-com-tls -> $TARGET_NS (controller $CONTROLLER_NS/$CONTROLLER_NAME)"
kubectl create secret tls ops-noizu-com-tls \
  --cert="$CRT" --key="$KEY" \
  --namespace "$TARGET_NS" \
  --dry-run=client -o yaml \
  | kubeseal \
      --controller-namespace "$CONTROLLER_NS" \
      --controller-name "$CONTROLLER_NAME" \
      --format yaml \
  > "$OUT"

echo "Wrote $OUT"