#!/usr/bin/env bash
# Generate the infra DB/registry credentials ONCE, then seal them into committed
# SealedSecrets. The sealed files are the source of truth — Terraform only
# applies them (secrets.tf), so the values can never be regenerated by an apply.
#
# Plaintext is written to the gitignored secrets store so the values can be
# recovered and re-sealed (e.g. after a controller key rotation) without change:
#   <repo>/.secrets/infra/values.env       (alnum values; safe to source)
#   <repo>/.secrets/infra/registry.htpasswd (bcrypt line)
# Re-running reuses those, so the SECRET VALUES stay stable across runs.
#
# Requires: kubectl + kubeseal, with the sealed-secrets controller running
# (installed by init into kube-system as sealed-secrets-controller). htpasswd
# (apache2-utils) if present, else falls back to `uv run --with bcrypt`.
#
#   ./seal-managed-secrets.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$HERE" rev-parse --show-toplevel)"

NS="${TARGET_NS:-infra}"
CNS="${CONTROLLER_NS:-kube-system}"
CNAME="${CONTROLLER_NAME:-sealed-secrets-controller}"
OUT="$HERE/secrets"
STORE="${INFRA_SECRETS_STORE:-$REPO_ROOT/.secrets/infra}"
VALUES="$STORE/values.env"
HTPASSWD_FILE="$STORE/registry.htpasswd"
REG_USER="${REGISTRY_USERNAME:-ops}"

# Per-app Postgres roles — keep in sync with infra/postgres.tf local.pg_app_dbs.
APPS=(AUTHENTIK BOTTLECRM DOCMOST GHOST INFISICAL LANGFUSE LISTMONK N8N NEXTCLOUD
      PENPOT PHOENIX PLANE POSTHOG POSTIZ TAIGA WEBSTUDIO)

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"; }

mkdir -p "$STORE" "$OUT"
chmod 700 "$STORE" 2>/dev/null || true

# 1. Generate values once, then top up any missing keys. Existing values are
#    never rewritten, so they stay stable across runs; only NEW keys (e.g. an app
#    added to APPS later) get appended. This makes adding an app non-destructive.
[[ -f "$VALUES" ]] && echo ">> reusing values from $VALUES" || echo ">> creating $VALUES"
touch "$VALUES"; chmod 600 "$VALUES"

ensure() {  # KEY VALUE — append "KEY=VALUE" only if KEY is not already set.
  local key="$1" val="$2"
  if ! grep -q "^${key}=" "$VALUES"; then
    printf '%s=%s\n' "$key" "$val" >> "$VALUES"
    echo "   + ${key}"
  fi
}

ensure POSTGRES_PASSWORD "$(rand 32)"
for a in "${APPS[@]}"; do
  ensure "${a}_DB_USER" "$(printf '%s' "$a" | tr '[:upper:]' '[:lower:]')"
  ensure "${a}_DB_PASSWORD" "$(rand 32)"
done
ensure SIGNOZ_TOKENIZER_JWT_SECRET "$(rand 64)"
ensure REGISTRY_USERNAME "${REG_USER}"
ensure REGISTRY_PASSWORD "$(rand 24)"

# shellcheck disable=SC1090
source "$VALUES"

# bcrypt htpasswd line (stored separately — it contains $ that would break env sourcing).
if [[ ! -f "$HTPASSWD_FILE" ]]; then
  if command -v htpasswd > /dev/null; then
    htpasswd -nbBC 10 "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" > "$HTPASSWD_FILE"
  else
    uv run --with bcrypt python - "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" > "$HTPASSWD_FILE" <<'PY'
import sys, bcrypt
u, p = sys.argv[1], sys.argv[2]
print(f"{u}:" + bcrypt.hashpw(p.encode(), bcrypt.gensalt(10)).decode())
PY
  fi
  chmod 600 "$HTPASSWD_FILE"
fi
REGISTRY_HTPASSWD="$(cat "$HTPASSWD_FILE")"

seal() {  # <secret-name> <kubectl --from-literal args...>
  local name="$1"; shift
  kubectl create secret generic "$name" -n "$NS" "$@" --dry-run=client -o yaml \
    | kubeseal --controller-namespace "$CNS" --controller-name "$CNAME" --format yaml \
    > "$OUT/$name.sealedsecret.yaml"
  echo "   sealed $name"
}

echo ">> sealing into $OUT (controller $CNS/$CNAME, ns $NS)"

pg_args=(--from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD")
for a in "${APPS[@]}"; do
  uvar="${a}_DB_USER"; pvar="${a}_DB_PASSWORD"
  pg_args+=(--from-literal="${uvar}=${!uvar}" --from-literal="${pvar}=${!pvar}")
done
seal postgres-secrets "${pg_args[@]}"
seal clickhouse-secrets --from-literal=SIGNOZ_TOKENIZER_JWT_SECRET="$SIGNOZ_TOKENIZER_JWT_SECRET"
seal registry-basic-auth --from-literal=auth="$REGISTRY_HTPASSWD"

echo
echo "Done. Commit the *.sealedsecret.yaml files in $OUT."
echo "Plaintext (gitignored): $VALUES"
echo "Registry login: ${REGISTRY_USERNAME} / ${REGISTRY_PASSWORD}"
