static-site:
  nameOverride: gotta-cc
  fullnameOverride: gotta-cc
  domain: gotta.cc
  image: ops.noizu.com/app-gotta-cc:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: gotta-cc-tls

