replicas: 1
domain: derobot.is

teaser:
  image: ops.noizu.com/derobot.is/teaser:latest
  port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

imagePullSecrets:
  - name: ops-registry-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
  cloudflareOnly: true

tls:
  enabled: true
  secretName: derobotis-tls
  infisical:
    enabled: true
    resyncInterval: 300
    credentialsSecret: universal-auth-credentials
    credentialsNamespace: infisical-operator-system
    projectSlug: k8-infra
    envSlug: prod
    secretsPath: "/apps/tls/derobotis"
    crtKey: DEROBOTIS_TLS_CRT
    keyKey: DEROBOTIS_TLS_KEY
