static-site:
  nameOverride: jailbreakingsite
  fullnameOverride: jailbreakingsite
  domain: jailbreakingsite.com
  image: ops.noizu.com/app-jailbreakingsite:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: jailbreakingsite-com-tls

