apiVersion: v1
kind: Service
metadata:
  name: {{ include "npl-mcp.fullname" . }}
  labels:
    {{- include "npl-mcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "npl-mcp.selectorLabels" . | nindent 4 }}
