{{- if and .Values.tls.enabled .Values.tls.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.tls.secretName }}
  labels:
    {{- include "npl-mcp.labels" . | nindent 4 }}
spec:
  hostAPI: {{ .Values.tls.infisical.hostAPI }}
  resyncInterval: 300
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.tls.infisical.secretName }}
        secretNamespace: {{ .Values.tls.infisical.credentialsNamespace }}
  managedSecretReference:
    secretName: {{ .Values.tls.secretName }}
    secretNamespace: {{ .Release.Namespace }}
    secretType: kubernetes.io/tls
    creationPolicy: Owner
    template:
      data:
        tls.crt: "{{ `{{ .` }}{{ .Values.tls.infisical.crtKey }}{{ `.Value }}` }}"
        tls.key: "{{ `{{ .` }}{{ .Values.tls.infisical.keyKey }}{{ `.Value }}` }}"
  tokenSecretReference:
    secretName: ""
    secretNamespace: ""
    secretType: Opaque
    creationPolicy: Owner
{{- with .Values.tls.infisical }}
  scope:
    projectSlug: {{ .projectSlug }}
    envSlug: {{ .envSlug }}
    secretsPath: {{ .secretsPath }}
{{- end }}
{{- end }}
