server {
    listen 80;
    location = /.well-known/mta-sts.txt {
        root /usr/share/nginx/html;
        add_header Content-Type "text/plain; charset=utf-8";
        add_header Cache-Control "max-age=86400";
    }
    location / {
        return 404;
    }
}
