replicas: 1
domain: bladeofeternity.com

image: ops.noizu.com/bladeofeternity.com/web:latest
port: 3000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

imagePullSecrets:
  - name: ops-registry-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  cloudflareOnly: true

tls:
  enabled: true
  secretName: bladeofeternity-tls
  infisical:
    enabled: true
    resyncInterval: 300
    credentialsSecret: universal-auth-credentials
    credentialsNamespace: infra
    projectSlug: k8-infra
    envSlug: prod
    hostAPI: https://infisical.noizu.com/api
    secretsPath: "/apps/tls/bladeofeternity"
    crtKey: BLADEOFETERNITY_TLS_CRT
    keyKey: BLADEOFETERNITY_TLS_KEY
