static-site:
  nameOverride: infra-portal
  fullnameOverride: infra-portal
  domain: infra.noizu.com
  image: ops.noizu.com/infra.noizu.com/web:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: noizu-com-tls
    infisical:
      enabled: false
