SUBDIRS := auto-sudo direnv-config github-utils make-repo misc-git-utils quick-gist remote-tunnel secret-bucket tabbing-on zellij
SUBDIR_PREFIX := shell/
SUBDIR_DESCRIPTION := Shell and terminal utilities

include ../mk/subdirs.mk
