export { Tabs, TabsShowcase } from './Tabs';
export type { TabsProps, TabsVariant, TabItem } from './Tabs';
export { BarWithUnderline07 } from './BarWithUnderline07';
export { FullWidthTabsWithUnderline06 } from './FullWidthTabsWithUnderline06';
export { Simple09 } from './Simple09';
export { TabsInPills03 } from './TabsInPills03';
export { TabsInPillsOnGray04 } from './TabsInPillsOnGray04';
export { TabsInPillsWithBrandColor05 } from './TabsInPillsWithBrandColor05';
export { TabsWithUnderline01 } from './TabsWithUnderline01';
export { TabsWithUnderlineAndBadges08 } from './TabsWithUnderlineAndBadges08';
export { TabsWithUnderlineAndIcons02 } from './TabsWithUnderlineAndIcons02';
