apiVersion: v2
name: noizu-site
description: "noizu.com static website"
version: 0.1.0
appVersion: "0.1.0"
type: application
keywords:
  - noizu
  - static-site
  - nginx
maintainers:
  - name: Keith Brings
    email: keith.brings@noizu.com
sources:
  - https://github.com/the-robot-lives/incubator
