replicas: 1
domain: noizu.com

image: ops.noizu.com/noizu-website:latest
port: 80

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - name: ops-registry-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  cloudflareOnly: true

tls:
  enabled: true
  secretName: noizu-com-tls
  infisical:
    enabled: true
    resyncInterval: 300
    hostAPI: "https://infisical.noizu.com/api"
    credentialsSecret: universal-auth-credentials
    credentialsNamespace: infisical-operator-system
    projectSlug: k8-infra
    envSlug: prod
    secretsPath: "/shared/tls"
    crtKey: TLS_CRT
    keyKey: TLS_KEY
    caKey: CLOUDFLARE_CA_CRT
