#!/usr/bin/env bash
# Generates .env for docker-compose (always) and optionally
# backend/.env + frontend/.env for bare-metal dev.
#
# Usage:
#   ./scripts/gen-env.sh <slug> <db_name> <redis_db> <project_dir> <registry> <host_port>

set -euo pipefail

SLUG="$1"
DB_NAME="$2"
REDIS_DB="$3"
PROJECT_DIR="$4"
REGISTRY="${5:-ops.noizu.com}"
HOST_PORT="${6:-8080}"

SECRET_KEY=$(openssl rand -base64 48)
GUARDIAN_KEY=$(openssl rand -base64 48)
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

if [ -f .env ]; then
  echo ""
  echo "WARNING: .env already exists. Overwrite? [y/N]"
  read -r confirm
  [ "$confirm" = "y" ] || [ "$confirm" = "Y" ] || { echo "Aborted."; exit 1; }
fi

# ── Docker .env (used by docker-compose, backend container env_file) ──
cat > .env <<ENVEOF
# Generated by make init — ${TIMESTAMP}
# Project: ${PROJECT_DIR}

# ── Project identity ─────────────────────────────────────────────
PROJECT_DIR=${PROJECT_DIR}
PROJECT_SLUG=${SLUG}
COMPOSE_PROJECT_NAME=${PROJECT_DIR//\./-}
REGISTRY=${REGISTRY}
TAG=latest

# ── Postgres (container hostname = "db" on lets-go_default network) ──
DATABASE_URL=ecto://${SLUG}:${SLUG}_dev@db:5432/${DB_NAME}

# ── Redis (container hostname = "redis" on lets-go_default network) ──
REDIS_URL=redis://${SLUG}:${SLUG}_dev@redis:6379/${REDIS_DB}
REDIS_KEY_PREFIX=${SLUG}:

# ── Secrets ──────────────────────────────────────────────────────
SECRET_KEY_BASE=${SECRET_KEY}
GUARDIAN_SECRET_KEY=${GUARDIAN_KEY}

# ── App ──────────────────────────────────────────────────────────
PHX_HOST=${PROJECT_DIR}
NEXT_PUBLIC_API_URL=

# ── Port (nginx, host-side) ─────────────────────────────────────
PORT=${HOST_PORT}
ENVEOF

# ── Local dev .env files (for running mix/npm directly) ──────────
cat > backend/.env <<ENVEOF
# Local dev — generated by make init — ${TIMESTAMP}
# Source this before running mix: source .env

DB_USER=${SLUG}
DB_PASS=${SLUG}_dev
DB_HOST=localhost
DB_NAME=${DB_NAME}
DB_PORT=5432

REDIS_URL=redis://${SLUG}:${SLUG}_dev@localhost:6379/${REDIS_DB}
REDIS_KEY_PREFIX=${SLUG}:

SECRET_KEY_BASE=${SECRET_KEY}
GUARDIAN_SECRET_KEY=${GUARDIAN_KEY}

PORT=4000
ENVEOF

cat > frontend/.env <<ENVEOF
# Local dev — generated by make init
NEXT_PUBLIC_API_URL=http://localhost:4000
ENVEOF

echo ""
echo "Created:"
echo "  .env             → docker-compose (${SLUG}@db/${DB_NAME}, redis/${REDIS_DB})"
echo "  backend/.env     → local dev (${SLUG}@localhost/${DB_NAME})"
echo "  frontend/.env    → local dev (NEXT_PUBLIC_API_URL=http://localhost:4000)"
echo "  SECRET_KEY_BASE  → (generated)"
echo "  GUARDIAN_SECRET_KEY → (generated)"
echo ""
echo "Next: make build && make run"
