import type { ComponentType } from "react";

export interface ComponentEntry {
  name: string;
  exportName: string;
  loader: () => Promise<Record<string, ComponentType>>;
}

export interface ComponentGroup {
  label: string;
  href: string;
  entries: ComponentEntry[];
}

function reg(dir: string, exports: [string, string][]): ComponentEntry[] {
  return exports.map(([exportName, displayName]) => ({
    name: displayName,
    exportName,
    loader: () => import(`@styleguide-engine/components/tailwind-plus/${dir}`),
  }));
}

// =============================================================================
// APP UI
// =============================================================================

export const APP_UI: ComponentGroup[] = [
  {
    label: "Shells",
    href: "shells",
    entries: [
      ...reg("app-ui/application-shells/stacked", [
        ["BrandedNavWithCompactLighterPageHeader04", "Branded Nav With Compact Lighter Page Header"],
        ["BrandedNavWithLighterPageHeader07", "Branded Nav With Lighter Page Header"],
        ["BrandNavWithOverlap06", "Brand Nav With Overlap"],
        ["OnSubtleBackground02", "On Subtle Background"],
        ["TwoRowNavigationWithOverlap09", "Two Row Navigation With Overlap"],
        ["WithBottomBorder01", "With Bottom Border"],
        ["WithCompactLighterPageHeader08", "With Compact Lighter Page Header"],
        ["WithLighterPageHeader03", "With Lighter Page Header"],
        ["WithOverlap05", "With Overlap"],
      ]),
      ...reg("app-ui/application-shells/sidebar", [
        ["BrandSidebarWithHeader08", "Brand Sidebar With Header"],
        ["DarkSidebarWithHeader04", "Dark Sidebar With Header"],
        ["SidebarWithHeader03", "Sidebar With Header"],
        ["SimpleBrandSidebar07", "Simple Brand Sidebar"],
        ["SimpleDarkSidebar02", "Simple Dark Sidebar"],
        ["SimpleSidebar01", "Simple Sidebar"],
        ["WithConstrainedContentArea05", "With Constrained Content Area"],
        ["WithOffWhiteBackground06", "With Off White Background"],
      ]),
      ...reg("app-ui/application-shells/multi-column", [
        ["ConstrainedThreeColumn03", "Constrained Three Column"],
        ["ConstrainedWithStickyColumns04", "Constrained With Sticky Columns"],
        ["FullWidthSecondaryColumnOnRight02", "Full Width Secondary Column On Right"],
        ["FullWidthThreeColumn01", "Full Width Three Column"],
        ["FullWidthWithNarrowSidebar05", "Full Width With Narrow Sidebar"],
        ["FullWidthWithNarrowSidebarAndHeader06", "Full Width With Narrow Sidebar And Header"],
      ]),
    ],
  },
  {
    label: "Headings",
    href: "headings",
    entries: [
      ...reg("app-ui/headings/page-headings", [
        ["CardWithAvatarAndStats09", "Card With Avatar And Stats"],
        ["WithActions01", "With Actions"],
        ["WithActionsAndBreadcrumbs03", "With Actions And Breadcrumbs"],
        ["WithAvatarAndActions08", "With Avatar And Actions"],
        ["WithBannerImage07", "With Banner Image"],
        ["WithFiltersAndAction12", "With Filters And Action"],
        ["WithLogoMetaAndActions13", "With Logo Meta And Actions"],
        ["WithMetaActionsAndBreadcrumbs10", "With Meta Actions And Breadcrumbs"],
        ["WithMetaAndActions05", "With Meta And Actions"],
      ]),
      ...reg("app-ui/headings/card-headings", [
        ["Simple01", "Simple"],
        ["WithAction02", "With Action"],
        ["WithAvatarAndActions03", "With Avatar And Actions"],
        ["WithAvatarMetaAndDropdown06", "With Avatar Meta And Dropdown"],
        ["WithDescription05", "With Description"],
        ["WithDescriptionAndAction04", "With Description And Action"],
      ]),
      ...reg("app-ui/headings/section-headings", [
        ["Simple01", "Simple"],
        ["WithAction04", "With Action"],
        ["WithActions03", "With Actions"],
        ["WithActionsAndTabs07", "With Actions And Tabs"],
        ["WithBadgeAndDropdown10", "With Badge And Dropdown"],
        ["WithDescription02", "With Description"],
        ["WithInlineTabs08", "With Inline Tabs"],
        ["WithInputGroup05", "With Input Group"],
        ["WithLabel09", "With Label"],
        ["WithTabs06", "With Tabs"],
      ]),
    ],
  },
  {
    label: "Data Display",
    href: "data-display",
    entries: [
      ...reg("app-ui/data-display/description-lists", [
        ["LeftAligned01", "Left Aligned"],
        ["LeftAlignedInCard03", "Left Aligned In Card"],
        ["LeftAlignedStriped04", "Left Aligned Striped"],
        ["LeftAlignedWithInlineActions06", "Left Aligned With Inline Actions"],
        ["NarrowWithHiddenLabels06", "Narrow With Hidden Labels"],
        ["TwoColumn05", "Two Column"],
      ]),
      ...reg("app-ui/data-display/stats", [
        ["Simple02", "Simple"],
        ["SimpleInCards03", "Simple In Cards"],
        ["WithBrandIcon04", "With Brand Icon"],
        ["WithSharedBorders05", "With Shared Borders"],
        ["WithTrending01", "With Trending"],
      ]),
      ...reg("app-ui/data-display/calendars", [
        ["BorderlessSideBySide08", "Borderless Side By Side"],
        ["BorderlessStacked07", "Borderless Stacked"],
        ["DayView04", "Day View"],
        ["Double06", "Double"],
        ["MonthView02", "Month View"],
        ["SmallWithMeetings01", "Small With Meetings"],
        ["WeekView03", "Week View"],
        ["YearView05", "Year View"],
      ]),
    ],
  },
  {
    label: "Lists",
    href: "lists",
    entries: [
      ...reg("app-ui/lists/stacked-lists", [
        ["FullWidthWithConstrainedContent10", "Full Width With Constrained Content"],
        ["FullWidthWithLinks09", "Full Width With Links"],
        ["InCardWithLinks07", "In Card With Links"],
        ["Narrow11", "Narrow"],
        ["NarrowWithActions13", "Narrow With Actions"],
        ["NarrowWithBadges17", "Narrow With Badges"],
        ["NarrowWithSmallAvatars15", "Narrow With Small Avatars"],
        ["NarrowWithStickyHeadings12", "Narrow With Sticky Headings"],
        ["NarrowWithTruncatedContent14", "Narrow With Truncated Content"],
        ["Simple01", "Simple"],
        ["TwoColumnsWithLinks08", "Two Columns With Links"],
        ["WithBadgesButtonAndActionsMenu06", "With Badges Button And Actions Menu"],
        ["WithInlineLinksAndActionsMenu05", "With Inline Links And Actions Menu"],
        ["WithInlineLinksAndAvatarGroup04", "With Inline Links And Avatar Group"],
        ["WithLinks03", "With Links"],
      ]),
      ...reg("app-ui/lists/tables", [
        ["FullWidth04", "Full Width"],
        ["FullWidthWithAvatars19", "Full Width With Avatars"],
        ["FullWidthWithConstrainedContent04b", "Full Width With Constrained Content"],
        ["Simple01", "Simple"],
        ["SimpleInCard03", "Simple In Card"],
        ["WithAvatarsAndMultilineContent09", "With Avatars And Multiline Content"],
        ["WithBorder16", "With Border"],
        ["WithCheckboxes17", "With Checkboxes"],
        ["WithCondensedContent12", "With Condensed Content"],
        ["WithGroupedRows14", "With Grouped Rows"],
        ["WithHiddenColumnsOnMobile08", "With Hidden Columns On Mobile"],
        ["WithHiddenHeadings18", "With Hidden Headings"],
        ["WithSortableHeadings13", "With Sortable Headings"],
        ["WithStackedColumnsOnMobile07", "With Stacked Columns On Mobile"],
        ["WithStickyHeader10", "With Sticky Header"],
        ["WithStripedRows05", "With Striped Rows"],
        ["WithSummaryRows15", "With Summary Rows"],
        ["WithUppercaseHeadings06", "With Uppercase Headings"],
        ["WithVerticalLines11", "With Vertical Lines"],
      ]),
      ...reg("app-ui/lists/grid-lists", [
        ["ActionsWithSharedBorders05", "Actions With Shared Borders"],
        ["ContactCards02", "Contact Cards"],
        ["ContactCardsWithSmallPortrait01", "Contact Cards With Small Portrait"],
        ["HorizontalLinkCards04", "Horizontal Link Cards"],
        ["ImagesWithDetails06", "Images With Details"],
        ["LogosCardsWithDescriptionList07", "Logos Cards With Description List"],
        ["SimpleCards03", "Simple Cards"],
      ]),
      ...reg("app-ui/lists/feeds", [
        ["SimpleWithIcons01", "Simple With Icons"],
        ["WithComments02", "With Comments"],
        ["WithMultipleItemTypes03", "With Multiple Item Types"],
      ]),
    ],
  },
  {
    label: "Forms",
    href: "forms",
    entries: [
      ...reg("app-ui/forms/form-layouts", [
        ["LabelsOnLeft05", "Labels On Left"],
        ["Stacked01", "Stacked"],
        ["TwoColumn03", "Two Column"],
        ["TwoColumnWithCards04", "Two Column With Cards"],
      ]),
      ...reg("app-ui/forms/input-groups", [
        ["InputsWithInsetLabelsAndSharedBorders17", "Inputs With Inset Labels And Shared Borders"],
        ["InputsWithSharedBorders15", "Inputs With Shared Borders"],
        ["InputWithAddOn09", "Input With Add On"],
        ["InputWithCornerHint06", "Input With Corner Hint"],
        ["InputWithDisabledState04", "Input With Disabled State"],
        ["InputWithGrayBackgroundAndBottomBorder20", "Input With Gray Background And Bottom Border"],
        ["InputWithHiddenLabel05", "Input With Hidden Label"],
        ["InputWithInlineAddOn10", "Input With Inline Add On"],
        ["InputWithInlineLeadingAddOnAndTrailingDropdown13", "Input With Inline Leading Add On And Trailing Dropdown"],
        ["InputWithInlineLeadingAndTrailingAddOns11", "Input With Inline Leading And Trailing Add Ons"],
        ["InputWithInlineLeadingDropdown12", "Input With Inline Leading Dropdown"],
        ["InputWithInsetLabel16", "Input With Inset Label"],
        ["InputWithKeyboardShortcut21", "Input With Keyboard Shortcut"],
        ["InputWithLabel01", "Input With Label"],
        ["InputWithLabelAndHelpText02", "Input With Label And Help Text"],
        ["InputWithLeadingIcon07", "Input With Leading Icon"],
        ["InputWithLeadingIconAndTrailingButton14", "Input With Leading Icon And Trailing Button"],
        ["InputWithOverlappingLabel18", "Input With Overlapping Label"],
        ["InputWithPillShape19", "Input With Pill Shape"],
        ["InputWithTrailingIcon08", "Input With Trailing Icon"],
        ["InputWithValidationError03", "Input With Validation Error"],
      ]),
      ...reg("app-ui/forms/select-menus", [
        ["BrandedWithSupportingText07", "Branded With Supporting Text"],
        ["CustomWithAvatar05", "Custom With Avatar"],
        ["CustomWithCheckOnLeft03", "Custom With Check On Left"],
        ["CustomWithStatusIndicator04", "Custom With Status Indicator"],
        ["SimpleCustom02", "Simple Custom"],
        ["SimpleNative01", "Simple Native"],
        ["WithSecondaryText06", "With Secondary Text"],
      ]),
      ...reg("app-ui/forms/sign-in-forms", [
        ["Simple01", "Simple"],
        ["SimpleCard05", "Simple Card"],
        ["SimpleNoLabels03", "Simple No Labels"],
        ["SplitScreen04", "Split Screen"],
      ]),
      ...reg("app-ui/forms/textareas", [
        ["Simple01", "Simple"],
        ["WithAvatarAndActions02", "With Avatar And Actions"],
        ["WithPreviewButton05", "With Preview Button"],
        ["WithTitleAndPillActions04", "With Title And Pill Actions"],
        ["WithUnderlineAndActions03", "With Underline And Actions"],
      ]),
      ...reg("app-ui/forms/radio-groups", [
        ["Cards10", "Cards"],
        ["ColorPicker09", "Color Picker"],
        ["ListWithDescription03", "List With Description"],
        ["ListWithDescriptionsInPanel08", "List With Descriptions In Panel"],
        ["ListWithInlineDescription04", "List With Inline Description"],
        ["ListWithRadioOnRight05", "List With Radio On Right"],
        ["SimpleInlineList02", "Simple Inline List"],
        ["SimpleList01", "Simple List"],
        ["SimpleListWithRadioOnRight06", "Simple List With Radio On Right"],
        ["SimpleTable07", "Simple Table"],
        ["SmallCards11", "Small Cards"],
        ["StackedCards12", "Stacked Cards"],
      ]),
      ...reg("app-ui/forms/checkboxes", [
        ["ListWithCheckboxOnRight03", "List With Checkbox On Right"],
        ["ListWithDescription01", "List With Description"],
        ["ListWithInlineDescription02", "List With Inline Description"],
        ["SimpleListWithHeading04", "Simple List With Heading"],
      ]),
      ...reg("app-ui/forms/toggles", [
        ["ShortToggle02", "Short Toggle"],
        ["SimpleToggle01", "Simple Toggle"],
        ["ToggleWithIcon03", "Toggle With Icon"],
        ["WithLeftLabelAndDescription04", "With Left Label And Description"],
        ["WithRightLabel05", "With Right Label"],
      ]),
      ...reg("app-ui/forms/action-panels", [
        ["Simple01", "Simple"],
        ["SimpleWell07", "Simple Well"],
        ["WithButtonAtTopRight04", "With Button At Top Right"],
        ["WithButtonOnRight03", "With Button On Right"],
        ["WithInput06", "With Input"],
        ["WithLink02", "With Link"],
        ["WithToggle05", "With Toggle"],
        ["WithWell08", "With Well"],
      ]),
      ...reg("app-ui/forms/comboboxes", [
        ["Simple01", "Simple"],
        ["WithAvatar04", "With Avatar"],
        ["WithSecondaryText05", "With Secondary Text"],
        ["WithStatusIndicator03", "With Status Indicator"],
      ]),
    ],
  },
  {
    label: "Feedback",
    href: "feedback",
    entries: [
      ...reg("app-ui/feedback/alerts", [
        ["WithAccentBorder05", "With Accent Border"],
        ["WithActions03", "With Actions"],
        ["WithDescription01", "With Description"],
        ["WithDismissButton06", "With Dismiss Button"],
        ["WithLinkOnRight04", "With Link On Right"],
        ["WithList02", "With List"],
      ]),
      ...reg("app-ui/feedback/empty-states", [
        ["Simple01", "Simple"],
        ["WithDashedBorder02", "With Dashed Border"],
        ["WithRecommendations04", "With Recommendations"],
        ["WithRecommendationsGrid06", "With Recommendations Grid"],
        ["WithStartingPoints03", "With Starting Points"],
        ["WithTemplates05", "With Templates"],
      ]),
    ],
  },
  {
    label: "Navigation",
    href: "navigation",
    entries: [
      ...reg("app-ui/navigation/navbars", [
        ["DarkWithCenteredSearchAndSecondaryLinks09", "Dark With Centered Search And Secondary Links"],
        ["DarkWithQuickAction02", "Dark With Quick Action"],
        ["DarkWithSearch07", "Dark With Search"],
        ["Simple05", "Simple"],
        ["SimpleDark03", "Simple Dark"],
        ["SimpleDarkWithMenuButtonOnLeft01", "Simple Dark With Menu Button On Left"],
        ["SimpleWithMenuButtonOnLeft04", "Simple With Menu Button On Left"],
        ["WithCenteredSearchAndSecondaryLinks10", "With Centered Search And Secondary Links"],
        ["WithQuickAction06", "With Quick Action"],
        ["WithSearch08", "With Search"],
        ["WithSearchInColumnLayout11", "With Search In Column Layout"],
      ]),
      ...reg("app-ui/navigation/pagination", [
        ["CardFooterWithPageButtons01", "Card Footer With Page Buttons"],
        ["CenteredPageNumbers02", "Centered Page Numbers"],
        ["SimpleCardFooter03", "Simple Card Footer"],
      ]),
      ...reg("app-ui/navigation/tabs", [
        ["BarWithUnderline07", "Bar With Underline"],
        ["FullWidthTabsWithUnderline06", "Full Width Tabs With Underline"],
        ["Simple09", "Simple"],
        ["TabsInPills03", "Tabs In Pills"],
        ["TabsInPillsOnGray04", "Tabs In Pills On Gray"],
        ["TabsInPillsWithBrandColor05", "Tabs In Pills With Brand Color"],
        ["TabsWithUnderline01", "Tabs With Underline"],
        ["TabsWithUnderlineAndBadges08", "Tabs With Underline And Badges"],
        ["TabsWithUnderlineAndIcons02", "Tabs With Underline And Icons"],
      ]),
      ...reg("app-ui/navigation/vertical-navigation", [
        ["OnGray06", "On Gray"],
        ["Simple01", "Simple"],
        ["WithBadges02", "With Badges"],
        ["WithIcons04", "With Icons"],
        ["WithIconsAndBadges03", "With Icons And Badges"],
        ["WithSecondaryNavigation05", "With Secondary Navigation"],
      ]),
      ...reg("app-ui/navigation/sidebar-navigation", [
        ["Brand05", "Brand"],
        ["Dark02", "Dark"],
        ["Light01", "Light"],
        ["WithExpandableSections03", "With Expandable Sections"],
        ["WithSecondaryNavigation04", "With Secondary Navigation"],
      ]),
      ...reg("app-ui/navigation/breadcrumbs", [
        ["Contained01", "Contained"],
        ["FullWidthBar02", "Full Width Bar"],
        ["SimpleWithChevrons03", "Simple With Chevrons"],
        ["SimpleWithSlashes04", "Simple With Slashes"],
      ]),
      ...reg("app-ui/navigation/progress-bars", [
        ["Bullets03", "Bullets"],
        ["BulletsAndText06", "Bullets And Text"],
        ["Circles05", "Circles"],
        ["CirclesWithText07", "Circles With Text"],
        ["Panels02", "Panels"],
        ["PanelsWithBorder04", "Panels With Border"],
        ["ProgressBar08", "Progress Bar"],
        ["Simple01", "Simple"],
      ]),
      ...reg("app-ui/navigation/command-palettes", [
        ["SemiTransparentWithIcons06", "Semi Transparent With Icons"],
        ["Simple01", "Simple"],
        ["SimpleWithPadding02", "Simple With Padding"],
        ["WithFooter09", "With Footer"],
        ["WithGroups08", "With Groups"],
        ["WithIcons05", "With Icons"],
        ["WithImagesAndDescriptions04", "With Images And Descriptions"],
        ["WithPreview03", "With Preview"],
      ]),
    ],
  },
  {
    label: "Overlays",
    href: "overlays",
    entries: [
      ...reg("app-ui/overlays/modal-dialogs", [
        ["CenteredWithSingleAction01", "Centered With Single Action"],
        ["CenteredWithWideButtons02", "Centered With Wide Buttons"],
        ["SimpleAlert03", "Simple Alert"],
        ["SimpleWithDismissButton04", "Simple With Dismiss Button"],
        ["SimpleWithGrayFooter05", "Simple With Gray Footer"],
        ["SimpleWithLeftAlignedButtons06", "Simple With Left Aligned Buttons"],
      ]),
      ...reg("app-ui/overlays/drawers", [
        ["ContactListExample08", "Contact List Example"],
        ["CreateProjectFormExample06", "Create Project Form Example"],
        ["Empty01", "Empty"],
        ["EmptyWide01a", "Empty Wide"],
        ["FileDetailsExample09", "File Details Example"],
        ["UserProfileExample07", "User Profile Example"],
        ["WideCreateProjectFormExample06a", "Wide Create Project Form Example"],
        ["WideUserProfileExample07a", "Wide User Profile Example"],
        ["WithBackgroundOverlay02", "With Background Overlay"],
        ["WithBrandedHeader04", "With Branded Header"],
        ["WithCloseButtonOnOutside03", "With Close Button On Outside"],
        ["WithStickyFooter05", "With Sticky Footer"],
      ]),
      ...reg("app-ui/overlays/notifications", [
        ["Condensed02", "Condensed"],
        ["Simple01", "Simple"],
        ["WithActionsBelow03", "With Actions Below"],
        ["WithAvatar04", "With Avatar"],
        ["WithButtonsBelow06", "With Buttons Below"],
        ["WithSplitButtons05", "With Split Buttons"],
      ]),
    ],
  },
  {
    label: "Elements",
    href: "elements",
    entries: [
      ...reg("app-ui/elements/avatars", [
        ["AvatarGroupStackedBottomToTop09", "Avatar Group Stacked Bottom To Top"],
        ["AvatarGroupStackedTopToBottom10", "Avatar Group Stacked Top To Bottom"],
        ["CircularAvatars01", "Circular Avatars"],
        ["CircularAvatarsWithBottomNotification05", "Circular Avatars With Bottom Notification"],
        ["CircularAvatarsWithPlaceholderIcon07", "Circular Avatars With Placeholder Icon"],
        ["CircularAvatarsWithPlaceholderInitials08", "Circular Avatars With Placeholder Initials"],
        ["CircularAvatarsWithTopNotification03", "Circular Avatars With Top Notification"],
        ["RoundedAvatars02", "Rounded Avatars"],
        ["RoundedAvatarsWithBottomNotification06", "Rounded Avatars With Bottom Notification"],
        ["RoundedAvatarsWithTopNotification04", "Rounded Avatars With Top Notification"],
        ["WithText11", "With Text"],
      ]),
      ...reg("app-ui/elements/badges", [
        ["Flat08", "Flat"],
        ["FlatPill09", "Flat Pill"],
        ["FlatPillWithDot11", "Flat Pill With Dot"],
        ["FlatWithDot10", "Flat With Dot"],
        ["FlatWithRemoveButton12", "Flat With Remove Button"],
        ["PillWithBorder05", "Pill With Border"],
        ["PillWithBorderAndDot06", "Pill With Border And Dot"],
        ["SmallFlat14", "Small Flat"],
        ["SmallFlatPill16", "Small Flat Pill"],
        ["SmallFlatPillWithDot18", "Small Flat Pill With Dot"],
        ["SmallFlatWithDot17", "Small Flat With Dot"],
        ["SmallPillWithBorder15", "Small Pill With Border"],
        ["SmallWithBorder13", "Small With Border"],
        ["WithBorder01", "With Border"],
        ["WithBorderAndDot03", "With Border And Dot"],
        ["WithBorderRemoveButton07", "With Border Remove Button"],
      ]),
      ...reg("app-ui/elements/buttons", [
        ["ButtonsWithLeadingIcon06", "Buttons With Leading Icon"],
        ["ButtonsWithTrailingIcon07", "Buttons With Trailing Icon"],
        ["CircularButtons10", "Circular Buttons"],
        ["PrimaryButtons01", "Primary Buttons"],
        ["RoundedPrimaryButtons08", "Rounded Primary Buttons"],
        ["RoundedSecondaryButtons09", "Rounded Secondary Buttons"],
        ["SecondaryButtons02", "Secondary Buttons"],
        ["SoftButtons05", "Soft Buttons"],
      ]),
      ...reg("app-ui/elements/button-groups", [
        ["Basic01", "Basic"],
        ["IconOnly02", "Icon Only"],
        ["WithCheckboxAndDropdown05", "With Checkbox And Dropdown"],
        ["WithDropdown04", "With Dropdown"],
        ["WithStat03", "With Stat"],
      ]),
      ...reg("app-ui/elements/dropdowns", [
        ["Simple01", "Simple"],
        ["WithDividers02", "With Dividers"],
        ["WithIcons03", "With Icons"],
        ["WithMinimalMenuIcon04", "With Minimal Menu Icon"],
        ["WithSimpleHeader05", "With Simple Header"],
      ]),
    ],
  },
  {
    label: "Layout",
    href: "layout",
    entries: [
      ...reg("app-ui/layout/cards", [
        ["BasicCard01", "Basic Card"],
        ["CardEdgeToEdgeOnMobile02", "Card Edge To Edge On Mobile"],
        ["CardWithFooter04", "Card With Footer"],
        ["CardWithGrayBody07", "Card With Gray Body"],
        ["CardWithGrayFooter06", "Card With Gray Footer"],
        ["CardWithHeader03", "Card With Header"],
        ["CardWithHeaderAndFooter05", "Card With Header And Footer"],
        ["Well08", "Well"],
        ["WellEdgeToEdgeOnMobile10", "Well Edge To Edge On Mobile"],
        ["WellOnGray09", "Well On Gray"],
      ]),
      ...reg("app-ui/layout/containers", [
        ["ConstrainedToBreakpointWithPaddedContent04", "Constrained To Breakpoint With Padded Content"],
        ["ConstrainedWithPaddedContent02", "Constrained With Padded Content"],
        ["FullWidthOnMobileConstrainedToBreakpointWithPaddedContentAboveMobile03", "Full Width On Mobile Constrained To Breakpoint With Padded Content Above Mobile"],
        ["FullWidthOnMobileConstrainedWithPaddedContentAbove01", "Full Width On Mobile Constrained With Padded Content Above"],
        ["NarrowConstrainedWithPaddedContent05", "Narrow Constrained With Padded Content"],
      ]),
      ...reg("app-ui/layout/dividers", [
        ["WithButton06", "With Button"],
        ["WithIcon02", "With Icon"],
        ["WithLabel01", "With Label"],
        ["WithLabelOnLeft03", "With Label On Left"],
        ["WithTitle04", "With Title"],
        ["WithTitleAndButton07", "With Title And Button"],
        ["WithTitleOnLeft05", "With Title On Left"],
        ["WithToolbar08", "With Toolbar"],
      ]),
      ...reg("app-ui/layout/list-containers", [
        ["CardWithDividers02", "Card With Dividers"],
        ["CardWithDividersFullWidthOnMobile03", "Card With Dividers Full Width On Mobile"],
        ["FlatCardWithDividers06", "Flat Card With Dividers"],
        ["SeparateCards04", "Separate Cards"],
        ["SeparateCardsFullWidthOnMobile05", "Separate Cards Full Width On Mobile"],
        ["SimpleWithDividers01", "Simple With Dividers"],
        ["SimpleWithDividersFullWidthOnMobile07", "Simple With Dividers Full Width On Mobile"],
      ]),
      ...reg("app-ui/layout/media-objects", [
        ["AlignedToBottom03", "Aligned To Bottom"],
        ["AlignedToCenter02", "Aligned To Center"],
        ["Basic01", "Basic"],
        ["BasicResponsive06", "Basic Responsive"],
        ["MediaOnRight05", "Media On Right"],
        ["Nested08", "Nested"],
        ["StretchedToFit04", "Stretched To Fit"],
        ["WideResponsive07", "Wide Responsive"],
      ]),
    ],
  },
  {
    label: "Pages",
    href: "pages",
    entries: [
      ...reg("app-ui/page-examples/home-screens", [
        ["Sidebar01", "Sidebar"],
        ["Stacked02", "Stacked"],
      ]),
      ...reg("app-ui/page-examples/detail-screens", [
        ["Sidebar01", "Sidebar"],
        ["Stacked02", "Stacked"],
      ]),
      ...reg("app-ui/page-examples/settings-screens", [
        ["Sidebar01", "Sidebar"],
        ["Stacked02", "Stacked"],
      ]),
    ],
  },
];

// =============================================================================
// MARKETING
// =============================================================================

export const MARKETING: ComponentGroup[] = [
  {
    label: "Heroes",
    href: "heroes",
    entries: [
      ...reg("marketing/sections/heroes", [
        ["SimpleCentered01", "Simple Centered"],
        ["SimpleCenteredWithBackgroundImage05", "Simple Centered With Background Image"],
        ["SplitWithBorderedScreenshot03", "Split With Bordered Screenshot"],
        ["SplitWithCodeExample04", "Split With Code Example"],
        ["SplitWithImage09", "Split With Image"],
        ["SplitWithScreenshot02", "Split With Screenshot"],
        ["WithAngledImageOnRight10", "With Angled Image On Right"],
        ["WithAppScreenshot07", "With App Screenshot"],
        ["WithBorderedAppScreenshot06", "With Bordered App Screenshot"],
        ["WithImageTiles11", "With Image Tiles"],
        ["WithOffsetImage12", "With Offset Image"],
        ["WithPhoneMockup08", "With Phone Mockup"],
      ]),
    ],
  },
  {
    label: "Feature Sections",
    href: "feature-sections",
    entries: [
      ...reg("marketing/sections/feature-sections", [
        ["Centered2x2Grid19", "Centered 2x2 Grid"],
        ["ContainedInPanel12", "Contained In Panel"],
        ["Offset2x2Grid15", "Offset 2x2 Grid"],
        ["OffsetWithFeatureList17", "Offset With Feature List"],
        ["Simple18", "Simple"],
        ["Simple3x2Grid20", "Simple 3x2 Grid"],
        ["SimpleThreeColumnWithLargeIcons10", "Simple Three Column With Large Icons"],
        ["SimpleThreeColumnWithSmallIcons07", "Simple Three Column With Small Icons"],
        ["WithCodeExamplePanel16", "With Code Example Panel"],
        ["WithLargeBorderedScreenshot05", "With Large Bordered Screenshot"],
        ["WithLargeScreenshot03", "With Large Screenshot"],
        ["WithProductScreenshot01", "With Product Screenshot"],
        ["WithProductScreenshotOnLeft09", "With Product Screenshot On Left"],
        ["WithProductScreenshotPanel13", "With Product Screenshot Panel"],
        ["WithTestimonial14", "With Testimonial"],
      ]),
    ],
  },
  {
    label: "Bento Grids",
    href: "bento-grids",
    entries: [
      ...reg("marketing/sections/bento-grids", [
        ["ThreeColumnBentoGrid01", "Three Column Bento Grid"],
        ["TwoRowBentoGrid02", "Two Row Bento Grid"],
        ["TwoRowBentoGridWithThreeColumnSecondRow03", "Two Row Bento Grid With Three Column Second Row"],
      ]),
    ],
  },
  {
    label: "Pricing",
    href: "pricing",
    entries: [
      ...reg("marketing/sections/pricing", [
        ["FourTiersWithToggle11", "Four Tiers With Toggle"],
        ["SinglePriceWithDetails05", "Single Price With Details"],
        ["ThreeTiers06", "Three Tiers"],
        ["ThreeTiersWithDividers07", "Three Tiers With Dividers"],
        ["ThreeTiersWithEmphasizedTier08", "Three Tiers With Emphasized Tier"],
        ["ThreeTiersWithFeatureComparison14", "Three Tiers With Feature Comparison"],
        ["ThreeTiersWithLogosAndFeatureComparison03", "Three Tiers With Logos And Feature Comparison"],
        ["ThreeTiersWithToggle09", "Three Tiers With Toggle"],
        ["TwoTiersWithEmphasizedLeftTier02", "Two Tiers With Emphasized Left Tier"],
        ["TwoTiersWithEmphasizedRightTier01", "Two Tiers With Emphasized Right Tier"],
        ["TwoTiersWithExtraTier04", "Two Tiers With Extra Tier"],
        ["WithComparisonTable12", "With Comparison Table"],
      ]),
    ],
  },
  {
    label: "CTA Sections",
    href: "cta-sections",
    entries: [
      ...reg("marketing/sections/cta-sections", [
        ["CenteredOnDarkPanel03", "Centered On Dark Panel"],
        ["DarkPanelWithAppScreenshot01", "Dark Panel With App Screenshot"],
        ["SimpleCentered04", "Simple Centered"],
        ["SimpleCenteredOnBrand06", "Simple Centered On Brand"],
        ["SimpleCenteredWithGradient05", "Simple Centered With Gradient"],
        ["SimpleJustified07", "Simple Justified"],
        ["SimpleJustifiedOnSubtleBrand08", "Simple Justified On Subtle Brand"],
        ["SimpleStacked02", "Simple Stacked"],
        ["SplitWithImage09", "Split With Image"],
        ["TwoColumnsWithPhoto10", "Two Columns With Photo"],
        ["WithImageTiles11", "With Image Tiles"],
      ]),
    ],
  },
  {
    label: "Testimonials",
    href: "testimonials",
    entries: [
      ...reg("marketing/sections/testimonials", [
        ["Grid09", "Grid"],
        ["SideBySide06", "Side By Side"],
        ["SimpleCentered02", "Simple Centered"],
        ["SubtleGrid10", "Subtle Grid"],
        ["WithBackgroundImage05", "With Background Image"],
        ["WithLargeAvatar03", "With Large Avatar"],
        ["WithOverlappingImage04", "With Overlapping Image"],
        ["WithStarRating08", "With Star Rating"],
      ]),
    ],
  },
  {
    label: "Blog Sections",
    href: "blog-sections",
    entries: [
      ...reg("marketing/sections/blog-sections", [
        ["SingleColumn04", "Single Column"],
        ["SingleColumnWithImages05", "Single Column With Images"],
        ["ThreeColumn01", "Three Column"],
        ["ThreeColumnWithBackgroundImages03", "Three Column With Background Images"],
        ["ThreeColumnWithImages02", "Three Column With Images"],
        ["WithFeaturedPost06", "With Featured Post"],
        ["WithPhotoAndList07", "With Photo And List"],
      ]),
    ],
  },
  {
    label: "Content Sections",
    href: "content-sections",
    entries: [
      ...reg("marketing/sections/content-sections", [
        ["Centered07", "Centered"],
        ["SplitWithImage06", "Split With Image"],
        ["TwoColumnsWithScreenshot04", "Two Columns With Screenshot"],
        ["WithImageTiles03", "With Image Tiles"],
        ["WithStickyProductScreenshot01", "With Sticky Product Screenshot"],
        ["WithTestimonial02", "With Testimonial"],
        ["WithTestimonialAndStats05", "With Testimonial And Stats"],
      ]),
    ],
  },
  {
    label: "Contact Sections",
    href: "contact-sections",
    entries: [
      ...reg("marketing/sections/contact-sections", [
        ["Centered01", "Centered"],
        ["SideBySideGrid02", "Side By Side Grid"],
        ["SimpleCentered06", "Simple Centered"],
        ["SimpleFourColumn05", "Simple Four Column"],
        ["SplitWithImage08", "Split With Image"],
        ["SplitWithPattern03", "Split With Pattern"],
        ["WithTestimonial07", "With Testimonial"],
      ]),
    ],
  },
  {
    label: "FAQ Sections",
    href: "faq-sections",
    entries: [
      ...reg("marketing/sections/faq-sections", [
        ["CenteredAccordion02", "Centered Accordion"],
        ["OffsetWithSupportingText01", "Offset With Supporting Text"],
        ["SideBySide04", "Side By Side"],
        ["ThreeColumns05", "Three Columns"],
        ["ThreeColumnsWithCenteredIntroduction07", "Three Columns With Centered Introduction"],
        ["TwoColumns08", "Two Columns"],
        ["TwoColumnsWithCenteredIntroduction10", "Two Columns With Centered Introduction"],
      ]),
    ],
  },
  {
    label: "Newsletter Sections",
    href: "newsletter-sections",
    entries: [
      ...reg("marketing/sections/newsletter-sections", [
        ["CenteredCard06", "Centered Card"],
        ["SideBySideOnCard07", "Side By Side On Card"],
        ["SideBySideWithDetails01", "Side By Side With Details"],
        ["SimpleSideBySide02", "Simple Side By Side"],
        ["SimpleSideBySideOnBrand04", "Simple Side By Side On Brand"],
        ["SimpleStacked05", "Simple Stacked"],
      ]),
    ],
  },
  {
    label: "Stats Sections",
    href: "stats-sections",
    entries: [
      ...reg("marketing/sections/stats-sections", [
        ["Simple01", "Simple"],
        ["SimpleGrid03", "Simple Grid"],
        ["SplitWithImage06", "Split With Image"],
        ["Stepped08", "Stepped"],
        ["Timeline07", "Timeline"],
        ["TwoColumnDescription09", "Two Column Description"],
        ["WithBackgroundImage05", "With Background Image"],
        ["WithDescription10", "With Description"],
      ]),
    ],
  },
  {
    label: "Team Sections",
    href: "team-sections",
    entries: [
      ...reg("marketing/sections/team-sections", [
        ["GridWithLargeRoundImages08", "Grid With Large Round Images"],
        ["GridWithRoundImages03", "Grid With Round Images"],
        ["LargeGridWithCards04", "Large Grid With Cards"],
        ["LargeImages02", "Large Images"],
        ["MediumImages09", "Medium Images"],
        ["SmallImages01", "Small Images"],
        ["WithImageAndShortParagraph05", "With Image And Short Paragraph"],
        ["WithVerticalImages06", "With Vertical Images"],
        ["WithVerticalImagesFullWidth07", "With Vertical Images Full Width"],
      ]),
    ],
  },
  {
    label: "Logo Clouds",
    href: "logo-clouds",
    entries: [
      ...reg("marketing/sections/logo-clouds", [
        ["Grid11", "Grid"],
        ["Simple09", "Simple"],
        ["SimpleLeftAligned05", "Simple Left Aligned"],
        ["SimpleWithCallToAction03", "Simple With Call To Action"],
        ["SimpleWithHeading01", "Simple With Heading"],
        ["SplitWithLogosOnRight07", "Split With Logos On Right"],
      ]),
    ],
  },
  {
    label: "Footers",
    href: "footers",
    entries: [
      ...reg("marketing/sections/footers", [
        ["N4ColumnSimple06", "4 Column Simple"],
        ["N4ColumnWithCallToAction04", "4 Column With Call To Action"],
        ["N4ColumnWithCompanyMission02", "4 Column With Company Mission"],
        ["N4ColumnWithNewsletter08", "4 Column With Newsletter"],
        ["N4ColumnWithNewsletterBelow10", "4 Column With Newsletter Below"],
        ["SimpleCentered12", "Simple Centered"],
        ["SimpleWithSocialLinks14", "Simple With Social Links"],
      ]),
    ],
  },
  {
    label: "Header Sections",
    href: "header-sections",
    entries: [
      ...reg("marketing/sections/header", [
        ["Centered02", "Centered"],
        ["CenteredWithBackgroundImage08", "Centered With Background Image"],
        ["CenteredWithEyebrow03", "Centered With Eyebrow"],
        ["Simple05", "Simple"],
        ["SimpleWithBackgroundImage07", "Simple With Background Image"],
        ["SimpleWithEyebrow06", "Simple With Eyebrow"],
        ["WithCards04", "With Cards"],
        ["WithStats01", "With Stats"],
      ]),
    ],
  },
  {
    label: "Headers",
    href: "headers",
    entries: [
      ...reg("marketing/elements/headers", [
        ["Constrained02", "Constrained"],
        ["FullWidth06", "Full Width"],
        ["OnBrandBackground04", "On Brand Background"],
        ["WithCallToAction07", "With Call To Action"],
        ["WithCenteredLogo12", "With Centered Logo"],
        ["WithFullWidthFlyoutMenu05", "With Full Width Flyout Menu"],
        ["WithIconsInMobileMenu09", "With Icons In Mobile Menu"],
        ["WithLeftAlignedNav10", "With Left Aligned Nav"],
        ["WithMultipleFlyoutMenus08", "With Multiple Flyout Menus"],
        ["WithRightAlignedNav11", "With Right Aligned Nav"],
        ["WithStackedFlyoutMenu01", "With Stacked Flyout Menu"],
      ]),
    ],
  },
  {
    label: "Flyout Menus",
    href: "flyout-menus",
    entries: [
      ...reg("marketing/elements/flyout-menus", [
        ["FullWidth04", "Full Width"],
        ["FullWidthTwoColumns02", "Full Width Two Columns"],
        ["Simple07", "Simple"],
        ["SimpleWithDescriptions05", "Simple With Descriptions"],
        ["StackedWithFooterActions01", "Stacked With Footer Actions"],
        ["StackedWithFooterList03", "Stacked With Footer List"],
        ["TwoColumn06", "Two Column"],
      ]),
    ],
  },
  {
    label: "Banners",
    href: "banners",
    entries: [
      ...reg("marketing/elements/banners", [
        ["BottomAligned07", "Bottom Aligned"],
        ["FloatingAtBottom08", "Floating At Bottom"],
        ["FloatingAtBottomCentered09", "Floating At Bottom Centered"],
        ["LeftAligned06", "Left Aligned"],
        ["OnBrand03", "On Brand"],
        ["OnDark02", "On Dark"],
        ["PrivacyNoticeCentered11", "Privacy Notice Centered"],
        ["PrivacyNoticeFullWidth13", "Privacy Notice Full Width"],
        ["PrivacyNoticeLeftAligned12", "Privacy Notice Left Aligned"],
        ["PrivacyNoticeRightAligned10", "Privacy Notice Right Aligned"],
        ["WithBackgroundGlow04", "With Background Glow"],
        ["WithButton01", "With Button"],
        ["WithLink05", "With Link"],
      ]),
    ],
  },
  {
    label: "404 Pages",
    href: "404-pages",
    entries: [
      ...reg("marketing/feedback/404-pages", [
        ["Simple01", "Simple"],
        ["SplitWithImage02", "Split With Image"],
        ["WithBackgroundImage05", "With Background Image"],
        ["WithNavbarAndFooter06", "With Navbar And Footer"],
        ["WithPopularPages03", "With Popular Pages"],
      ]),
    ],
  },
  {
    label: "Marketing Pages",
    href: "marketing-pages",
    entries: [
      ...reg("marketing/page-examples/landing-pages", [
        ["WithBackgroundImageHeroAndPricingSection03", "With Background Image Hero And Pricing Section"],
        ["WithLargeScreenshotAndTestimonial02", "With Large Screenshot And Testimonial"],
        ["WithMobileScreenshotAndTestimonialsGrid04", "With Mobile Screenshot And Testimonials Grid"],
        ["WithScreenshotsAndStats01", "With Screenshots And Stats"],
      ]),
      ...reg("marketing/page-examples/pricing-pages", [
        ["WithComparisonTable02", "With Comparison Table"],
        ["WithFourTiers01", "With Four Tiers"],
        ["WithThreeTiersAndTestimonials03", "With Three Tiers And Testimonials"],
      ]),
      ...reg("marketing/page-examples/about-pages", [
        ["WithImageTiles01", "With Image Tiles"],
        ["WithTimelineAndStats02", "With Timeline And Stats"],
        ["WithTwoColumnDescription03", "With Two Column Description"],
      ]),
    ],
  },
];

// =============================================================================
// ECOMMERCE
// =============================================================================

export const ECOMMERCE: ComponentGroup[] = [
  {
    label: "Products",
    href: "products",
    entries: [
      ...reg("ecommerce/components/product-lists", [
        ["CardWithFullDetails11", "Card With Full Details"],
        ["Simple06", "Simple"],
        ["WithBorderGrid08", "With Border Grid"],
        ["WithColorSwatchesAndHorizontalScrolling03", "With Color Swatches And Horizontal Scrolling"],
        ["WithCtaLink02", "With Cta Link"],
        ["WithImageOverlayAndAddButton05", "With Image Overlay And Add Button"],
        ["WithInlinePrice01", "With Inline Price"],
        ["WithInlnePriceAndCtaLink10", "With Inline Price And Cta Link"],
        ["WithSupportingText09", "With Supporting Text"],
        ["WithTallImages04", "With Tall Images"],
        ["WithTallImagesAndCtaLink07", "With Tall Images And Cta Link"],
      ]),
      ...reg("ecommerce/components/product-overviews", [
        ["SplitWithImageAndFeaturedDetails03", "Split With Image And Featured Details"],
        ["WithImageGalleryAndExpandableDetails02", "With Image Gallery And Expandable Details"],
        ["WithImageGrid04", "With Image Grid"],
        ["WithTabs05", "With Tabs"],
        ["WithTieredImages01", "With Tiered Images"],
      ]),
      ...reg("ecommerce/components/product-quickviews", [
        ["WithColorAndSizeSelector02", "With Color And Size Selector"],
        ["WithColorSelectorAndDescription04", "With Color Selector And Description"],
        ["WithColorSelectorSizeSelectorAndDetailsLink01", "With Color Selector Size Selector And Details Link"],
        ["WithLargeSizeSelector03", "With Large Size Selector"],
      ]),
      ...reg("ecommerce/components/product-features", [
        ["WithAlternatingSections07", "With Alternating Sections"],
        ["WithFadingImage02", "With Fading Image"],
        ["WithHeaderImagesAndDescriptions01", "With Header Images And Descriptions"],
        ["WithImageGrid03", "With Image Grid"],
        ["WithSplitImage05", "With Split Image"],
        ["WithSquareImages08", "With Square Images"],
        ["WithTabs06", "With Tabs"],
        ["WithTieredImages09", "With Tiered Images"],
        ["WithWideImages04", "With Wide Images"],
      ]),
      ...reg("ecommerce/components/category-previews", [
        ["ThreeColumn02", "Three Column"],
        ["ThreeColumnWithDescription04", "Three Column With Description"],
        ["WithBackgroundImageAndDetailOverlay03", "With Background Image And Detail Overlay"],
        ["WithImageBackgrounds01", "With Image Backgrounds"],
        ["WithScrollingCards05", "With Scrolling Cards"],
        ["WithSplitImages06", "With Split Images"],
      ]),
      ...reg("ecommerce/components/category-filters", [
        ["SidebarFilters05", "Sidebar Filters"],
        ["WithCenteredTextAndDropdownProductFilters01", "With Centered Text And Dropdown Product Filters"],
        ["WithDropdownProductFilters02", "With Dropdown Product Filters"],
        ["WithExpandableProductFilterPanel03", "With Expandable Product Filter Panel"],
        ["WithInlineActionsAndExpandableSidebarFilters04", "With Inline Actions And Expandable Sidebar Filters"],
      ]),
    ],
  },
  {
    label: "Shopping",
    href: "shopping",
    entries: [
      ...reg("ecommerce/components/shopping-carts", [
        ["Dialog05", "Dialog"],
        ["Drawer04", "Drawer"],
        ["Popover06", "Popover"],
        ["SingleColumn02", "Single Column"],
        ["TwoColumnWithQuantityDropdown01", "Two Column With Quantity Dropdown"],
        ["WithExtendedSummary03", "With Extended Summary"],
      ]),
      ...reg("ecommerce/components/order-summaries", [
        ["SimpleWithFullOrderDetails05", "Simple With Full Order Details"],
        ["WithLargeImagesAndProgressBars04", "With Large Images And Progress Bars"],
        ["WithProgressBars03", "With Progress Bars"],
        ["WithSplitImage01", "With Split Image"],
      ]),
      ...reg("ecommerce/components/order-history", [
        ["InvoiceList06", "Invoice List"],
        ["InvoiceListWithQuickActions07", "Invoice List With Quick Actions"],
        ["InvoicePanels03", "Invoice Panels"],
        ["InvoiceTable04", "Invoice Table"],
      ]),
    ],
  },
  {
    label: "Checkout",
    href: "checkout",
    entries: [
      ...reg("ecommerce/components/checkout-forms", [
        ["MultiStep03", "Multi Step"],
        ["SingleStepWithOrderSummary01", "Single Step With Order Summary"],
        ["SplitWithOrderSummary05", "Split With Order Summary"],
        ["WithMobileOrderSummaryOverlay02", "With Mobile Order Summary Overlay"],
        ["WithOrderSummarySidebar04", "With Order Summary Sidebar"],
      ]),
    ],
  },
  {
    label: "Reviews",
    href: "reviews",
    entries: [
      ...reg("ecommerce/components/reviews", [
        ["AvatarsWithSeparateDescription03", "Avatars With Separate Description"],
        ["MultiColumn01", "Multi Column"],
        ["SimpleWithAvatars04", "Simple With Avatars"],
        ["WithSummaryChart02", "With Summary Chart"],
      ]),
    ],
  },
  {
    label: "Promo",
    href: "promo",
    entries: [
      ...reg("ecommerce/components/promo-sections", [
        ["FullWidthWithBackgroundImage02", "Full Width With Background Image"],
        ["FullWidthWithBackgroundImageAndLargeContent08", "Full Width With Background Image And Large Content"],
        ["FullWidthWithOverlappingImageTiles03", "Full Width With Overlapping Image Tiles"],
        ["WithBackgroundImage04", "With Background Image"],
        ["WithFadingBackgroundImageAndTestimonials01", "With Fading Background Image And Testimonials"],
        ["WithImageTiles07", "With Image Tiles"],
        ["WithOffersAndSplitImage06", "With Offers And Split Image"],
        ["WithOverlappingImageTiles05", "With Overlapping Image Tiles"],
      ]),
      ...reg("ecommerce/components/incentives", [
        ["N2x2GridWithIllustrations06", "2x2 Grid With Illustrations"],
        ["N3ColumnWithIcons09", "3 Column With Icons"],
        ["N3ColumnWithIconsAndSupportingText08", "3 Column With Icons And Supporting Text"],
        ["N3ColumnWithIllustrationsAndCenteredText04", "3 Column With Illustrations And Centered Text"],
        ["N3ColumnWithIllustrationsAndHeader03", "3 Column With Illustrations And Header"],
        ["N3ColumnWithIllustrationsAndHeading05", "3 Column With Illustrations And Heading"],
        ["N3ColumnWithIllustrationsAndSplitHeader01", "3 Column With Illustrations And Split Header"],
        ["N4ColumnWithIllustrations02", "4 Column With Illustrations"],
      ]),
    ],
  },
  {
    label: "Navigation",
    href: "store-navigation",
    entries: [
      ...reg("ecommerce/components/store-navigation", [
        ["WithDoubleColumnAndPersistentMobileNav05", "With Double Column And Persistent Mobile Nav"],
        ["WithFeaturedCategories03", "With Featured Categories"],
        ["WithImageGrid01", "With Image Grid"],
        ["WithNavigationAndTieredFeaturedCategories04", "With Navigation And Tiered Featured Categories"],
        ["WithSimpleMenuAndPromo02", "With Simple Menu And Promo"],
      ]),
    ],
  },
  {
    label: "Ecommerce Pages",
    href: "ecommerce-pages",
    entries: [
      ...reg("ecommerce/page-examples/storefront-pages", [
        ["WithDarkNavAndFooter01", "With Dark Nav And Footer"],
        ["WithImageTilesAndFeatureSections03", "With Image Tiles And Feature Sections"],
        ["WithOffersAndTestimonials02", "With Offers And Testimonials"],
        ["WithOverlappingImageTilesAndPerks04", "With Overlapping Image Tiles And Perks"],
      ]),
      ...reg("ecommerce/page-examples/product-pages", [
        ["WithExpandableProductDetails03", "With Expandable Product Details"],
        ["WithFeaturedDetails04", "With Featured Details"],
        ["WithImageGrid02", "With Image Grid"],
        ["WithRelatedProducts01", "With Related Products"],
        ["WithTabsAndRelatedProducts05", "With Tabs And Related Products"],
      ]),
      ...reg("ecommerce/page-examples/category-pages", [
        ["WithImageHeaderAndDetailProductGrid02", "With Image Header And Detail Product Grid"],
        ["WithLargeImagesAndFiltersSidebar07", "With Large Images And Filters Sidebar"],
        ["WithProductGridAndPagination06", "With Product Grid And Pagination"],
        ["WithTextHeaderAndImageProductGrid01", "With Text Header And Image Product Grid"],
        ["WithTextHeaderAndSimpleProductGrid04", "With Text Header And Simple Product Grid"],
      ]),
      ...reg("ecommerce/page-examples/shopping-cart-pages", [
        ["SimpleWithPolicyGrid02", "Simple With Policy Grid"],
        ["WithPolicyGridAndExtendedSummary03", "With Policy Grid And Extended Summary"],
        ["WithRelatedProducts01", "With Related Products"],
      ]),
      ...reg("ecommerce/page-examples/checkout-pages", [
        ["MultiStep05", "Multi Step"],
        ["SingleStepWithOrderSummary02", "Single Step With Order Summary"],
        ["SplitWithOrderSummary07", "Split With Order Summary"],
        ["WithMobileOrderSummaryOverlay04", "With Mobile Order Summary Overlay"],
        ["WithOrderSummarySidebar01", "With Order Summary Sidebar"],
      ]),
      ...reg("ecommerce/page-examples/order-detail-pages", [
        ["SimpleWithFullOrderDetails05", "Simple With Full Order Details"],
        ["WithLargeImagesAndProgressBars04", "With Large Images And Progress Bars"],
        ["WithProgressBars03", "With Progress Bars"],
      ]),
      ...reg("ecommerce/page-examples/order-history-pages", [
        ["Simple01", "Simple"],
        ["WithInvoiceList06", "With Invoice List"],
        ["WithInvoiceListAndQuickActions02", "With Invoice List And Quick Actions"],
        ["WithInvoicePanels03", "With Invoice Panels"],
        ["WithInvoiceTables04", "With Invoice Tables"],
      ]),
    ],
  },
];
