static-site:
  nameOverride: robots-unite
  fullnameOverride: robots-unite
  domain: robots-unite.com
  image: ops.noizu.com/app-robots-unite:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: robots-unite-com-tls

