static-site:
  nameOverride: noizurpg
  fullnameOverride: noizurpg
  domain: noizurpg.com
  image: ops.noizu.com/app-noizurpg:latest
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: noizurpg-com-tls

