replicas: 1
domain: therobotlives.com

image: ops.noizu.com/therobotlives.com/web:v0.1.0
port: 3000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

imagePullSecrets:
  - name: ops-registry-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  cloudflareOnly: true

tls:
  enabled: true
  secretName: therobotlives-tls
  infisical:
    enabled: true
    resyncInterval: 300
    credentialsSecret: universal-auth-credentials
    credentialsNamespace: infisical-operator-system
    projectSlug: k8-infra
    envSlug: prod
    secretsPath: "/apps/tls/therobotlives"
    crtKey: THEROBOTLIVES_TLS_CRT
    keyKey: THEROBOTLIVES_TLS_KEY
